### PR TITLE
For Vulkan, disallow structures containing opaque types

### PR DESCRIPTION
**Pull request by jeffbolznv**
This change corresponds to a pending change to the Vulkan SPIR-V environment spec.

### CODE REVIEW

**Comment by jeffbolznv** [comment]
@johnkslang @alan-baker can you give me some advice on the shaderc-smoketests failures?

There appear to be two classes of failures. The first is new "Validation Failed" strings in some glslang gtests, which we agreed are expected, but how do we deal with the failures until glslang gold results are updated?

The second class of failures is two HlslLegalization tests that still have a struct with an opaque member, which at first glance seems like a bug in legalization. Any idea what's going on there?

**Comment by alan-baker** [comment]
The validator runs before the optimizer. Generally there are some extra options sent to the validator for unlegalized code (e.g. --relax-logical-pointer). If legalization is needed to address this issue, we'll need another option for the validator to disable this check until during legalization.

**Comment by johnkslang** [comment]
Yes, this is a common coding pattern for HLSL that the optimizer turns into Vulkan-legal SPIR-V, so it should be included in the set of things tolerated by the validator for pre-legalization validation.

**Comment by s-perron** [comment]
I'm thinking we should create 1 new options for the validator that covers everything.  We have `--relax-logical-pointer`, but it does not seem appropriate to disable this check with that option.  I also may need to create a new option for https://github.com/KhronosGroup/SPIRV-Tools/issues/2535.  We should add an option say "--pre-hlsl-legalization" and turn off this check if that option is enabled.

Then we would need changes to DXC and glslang to set that option when appropriate.

@jeffbolznv I can add the option in my upcoming PR, and then you can use it in this PR.  That assumes we are not in a hurry to merge this one.

**Comment by jeffbolznv** [comment]
That sounds good to me. It's not urgent to merge this.

**Comment by alan-baker** [comment]
@jeffbolznv the option was merged if you want to rebase.

**Comment by jeffbolznv** [comment]
Can somebody point me at that commit/option? Is anybody planning to add it to glslang, or should I do that?

**Comment by alan-baker** [comment]
e935dac9ef8a01fdb6d0a4b7898563e6f62d1081 added the option. I'm not aware of anyone currently adding the option to glslang's HLSL flow.

**Comment by jeffbolznv** [comment]
This finally passes CI, and is ready to merge.

**Comment by bkaradzic** [comment]
This change causes failure to build HLSL shaders containing code like:

```
struct BgfxSampler2D
{
	SamplerState m_sampler;
	Texture2D m_texture;
};
```

**Comment by Ace17** [comment]
This changes also causes failure to build HLSL shaders containing code like:
```
cbuffer MyCBuffer
{
    Texture2D myTexture;
    SamplerState mySampler;
}
```

**Comment by s-perron** [comment]
@bkaradzic  @Ace17 Can you open new issues against the HLSL compiler that you are using with an example that can be compiled?  This change is not wrong because it is implementing the Vulkan spec.  The compiler generating the SPIR-V might need to change.

**Comment by Ace17** [comment]
Here's the issue on the glslang project : https://github.com/KhronosGroup/glslang/issues/2754

**Comment by greg-lunarg** [comment]
@s-perron FWIW, my current plan is to handle #2754 completely in glslang; no changes should be required in spirv-opt legalization. See the issue for more details.

**Pull request merged**
