### PR TITLE
Vulkan 1.3

### PR DESCRIPTION
**Pull request by alan-baker**
* Add new environment enum for Vulkan 1,3
* Do not require --allow-localsizeid in Vulkan 1.3 to use LocalSizeId
  execution mode

### CODE REVIEW

**Comment by alan-baker** [comment]
FYI @mnetsch

**Comment by dnovillo** [comment]
Could you check the formatting?  ci-check-format is complaining.

**Review by dneto0 — APPROVED** [review]
Thanks!

**Comment by greg-lunarg** [comment]
Thanks! Could someone please post a canary branch with this code with the goal of updating stable branch.

**Comment by dnovillo** [comment]
> Thanks! Could someone please post a canary branch with this code with the goal of updating stable branch?

Working on it.  I'll let you know when I have something ready.

**Comment by dnovillo** [comment]
> > Thanks! Could someone please post a canary branch with this code with the goal of updating stable branch?
> 
> Working on it. I'll let you know when I have something ready.

Done.  The canary branch has been updated.  PTAL.

**Comment by greg-lunarg** [comment]
Thanks! Will do.
Greg

Greg Fischer

Senior Engineer

LunarG, Inc. - 3D Driver Innovations

***@***.*** ***@***.***>

**Pull request merged**
