### PR TITLE
Avoid accessing invalid iterator.

### PR DESCRIPTION
**Pull request by dekimir**
@umar456 @antiagainst @AWoloszyn @dneto0 @Qining PTAL

### CODE REVIEW

**Comment by umar456** [comment]
The iterator should still be valid after the if statement. The iterator that is incremented is part of the block_info struct and not the staged vector.

**Comment by dekimir** [comment]
It's actually `top` that's invalid, due to `staged.emplace_back()` on line 90.

**Comment by umar456** [comment]
'top' is a reference to the last block_info element and not an iterator.

**Comment by dekimir** [comment]
Yes, sorry -- wrong title.  But the bug is real, and this is the fix.

**Comment by umar456** [comment]
I don't understand the bug. I don't create an iterator for any of the containers being updated in that if statement.

**Comment by dekimir** [comment]
`emplace_back()` reallocates `staged` memory, invalidating the `top` reference.  Dereferencing `top` after that is invalid, and it raises an exception in the Windows debug build.

**Comment by umar456** [comment]
Ahh gotcha. Makes sense. +2

**Pull request merged**
