### PR TITLE
spirv-opt: Where possible make code agnostic of opencl/vulkan debuginfo

### PR DESCRIPTION
**Pull request by greg-lunarg**

### CODE REVIEW

**Comment by greg-lunarg** [comment]
@jaebaek Please review after it clears CI.

**Review by jaebaek — COMMENTED** [review]
I am worried that some instructions of nonsemantic.debug.info have operands different from the one of opencl.debug.info.100.
For example,
- `DebugDeclare` has additional operand in nonsemantic.debug.info
- all integer literals in opencl.debuginfo.100 must be variables/constants with integer types in nonsemantic.debug.info

Do you think this is fine considering the differences between those two specs?

**Comment by greg-lunarg** [comment]
This change still does not enable processing of NonSemantic.Vulkan.DebugInfo.100. The next several PRs will make the handle all of the differences between the two specs before enabling processing of the Vulkan debug info as well as add regression tests with instructions from the new spec. For the time being, I believe we only need to make sure we don't cause handling of OpenCL debug info to regress.

**Comment by jaebaek** [comment]
Makes sense. LGTM

**Review by s-perron — APPROVED** [review]

**Pull request merged**
