### PR TITLE
spirv-val: Add Vulkan image gather offset VUID

### PR DESCRIPTION
**Pull request by sfricke-samsung**
VUID-StandaloneSpirv-Offset-04663

### CODE REVIEW

**Comment by sfricke-samsung** [comment]
Internal Vulkan issue 2507 opened to figure out if the failing test using `OpFetchImage` is valid or not

**Comment by sfricke-samsung** [comment]
@alan-baker From the WG meeting, seems like there was some idea that there might be some "exclude list" or something for the glslang test as those tests are just making sure glslang outputs the same SPIR-V and that people using glslang run `spirv-val` and so its ok for this change to trigger those test files... not sure how the CI flow all works yet

**Comment by alan-baker** [comment]
If glslang is indeed emitting invalid SPIR-V (which can indeed be the case for HLSL) the process is that we merge this MR and then a roll of glslang's known good hashes needs updated and the expected test results also need updated.

**Comment by sfricke-samsung** [comment]
Here are the 3 failing tests lines that have the `Offset` in their ImageFetch

https://github.com/KhronosGroup/glslang/blob/master/Test/baseResults/hlsl.load.2dms.dx10.frag.out#L510
https://github.com/KhronosGroup/glslang/blob/master/Test/baseResults/hlsl.load.offset.dx10.frag.out#L804
https://github.com/KhronosGroup/glslang/blob/master/Test/baseResults/hlsl.load.offsetarray.dx10.frag.out#L676

**Comment by alan-baker** [comment]
I'm anticipating a few PRs (e.g. #4124, and validation for explicit layout) that will cause a similar issues. I'm going to hold off merging this until they are all ready and I can do a single update for glslang.

**Pull request merged**
