### PR TITLE
Revert "Temporarily add EmptyPass to prevent glslang from failing (#4004)"

### PR DESCRIPTION
**Pull request by jaebaek**
This reverts commit f7da527757140ae701be58274ce6db2f4234d9ff.

- The commit f7da5277 added EmptyPass that temporarily handles glslang
failure caused by missing PropagateLineInfoPass and
RedundantLineInfoElimPass. Now glslang does not use PropagateLineInfoPass
and RedundantLineInfoElimPass (https://github.com/KhronosGroup/glslang/pull/2440).
We can revert f7da5277.

### CODE REVIEW

**Comment by sugoi1** [comment]
Just FYI, some projects pull glslang through an archive, like one of these:
https://github.com/KhronosGroup/glslang/tags

Example:
https://github.com/powervr-graphics/Native_SDK/blob/master/external/glslang/CMakeLists.txt#L5

There isn't one containing your fix yet, it would be nice to have one before landing this.

**Comment by jaebaek** [comment]
Thank you for the heads-up.
Ok I will delay submitting this CL.

**Review by dnovillo — CHANGES_REQUESTED** [review]
Unclear whether this is still needed?

**Comment by jaebaek** [comment]
Right. Let me close this PR for now. We have to submit this PR after those projects (relying on glslang) adopt KhronosGroup/glslang#2440.

**Pull request closed without merging**
