### PR TITLE
Add support for KHR_ray_{query,tracing} extensions

### PR DESCRIPTION
**Pull request by dgkoch**

### CODE REVIEW

**Comment by dgkoch** [comment]
@s-perron trying this one.

**Comment by s-perron** [comment]
This is compiling correctly for the linux builds.  However, it is failing tests.  I'll look into those.

**Comment by dgkoch** [comment]
I'm fixing the code formatting issues.

**Comment by dgkoch** [comment]
what is the command to run the tests?

**Comment by s-perron** [comment]
I just pushed a fix for the tests and the formatting.  On Linux, I use cmake, so I run the tests using `ctest`.  I'm not sure how to do it on other platforms.

**Comment by dgkoch** [comment]
> On Linux, I use cmake, so I run the tests using `ctest`. I'm not sure how to do it on other platforms.

Yeah ctest works on mac as well, at least when you're in the right folder..

I had some formatting changes as well, so I picked your change and re-pushed.

**Comment by dgkoch** [comment]
hopefully last fix.. applied formatting fixes to the test fixes.

**Comment by dgkoch** [comment]
Thanks @s-perron looks like CI passed this time as well.

**Pull request merged**
