### PR TITLE
add tests for SPV_KHR_bit_instructions

### PR DESCRIPTION
**Pull request by bashbaug**
See: https://github.com/KhronosGroup/SPIRV-Registry/pull/120

See also: https://github.com/KhronosGroup/SPIRV-Headers/pull/225

### CODE REVIEW

**Comment by s-perron** [comment]
Looks like SpvCapabilityBitInstructions is not in spirv-headers yet.  We will have to wait for https://github.com/KhronosGroup/SPIRV-Headers/pull/225 to be merged first.

**Comment by alan-baker** [comment]
@bashbaug please push a forced change to pick up the new headers.

**Comment by bashbaug** [comment]
I believe the builds are failing due to:  https://github.com/KhronosGroup/SPIRV-Headers/pull/224

```
FAILED: source/CMakeFiles/SPIRV-Tools-shared.dir/val/validate_extensions.cpp.o
/usr/bin/g++  -DSPIRV_CHECK_CONTEXT -DSPIRV_COLOR_TERMINAL -DSPIRV_LINUX -DSPIRV_TIMER_ENABLED -DSPIRV_TOOLS_IMPLEMENTATION -DSPIRV_TOOLS_SHAREDLIB -DSPIRV_Tools_shared_EXPORTS -I../ -I../include -I. -I../external/spirv-headers/include -O2 -g -DNDEBUG -fPIC -fvisibility=hidden   -Wall -Wextra -Wnon-virtual-dtor -Wno-missing-field-initializers -Werror -std=c++11 -fno-exceptions -fno-rtti -Wno-long-long -Wshadow -Wundef -Wconversion -Wno-sign-conversion -std=gnu++11 -MD -MT source/CMakeFiles/SPIRV-Tools-shared.dir/val/validate_extensions.cpp.o -MF source/CMakeFiles/SPIRV-Tools-shared.dir/val/validate_extensions.cpp.o.d -o source/CMakeFiles/SPIRV-Tools-shared.dir/val/validate_extensions.cpp.o -c ../source/val/validate_extensions.cpp
../source/val/validate_extensions.cpp: In function 'spv_result_t spvtools::val::ValidateExtInst(spvtools::val::ValidationState_t&, const spvtools::val::Instruction*)':
../source/val/validate_extensions.cpp:2683:12: error: enumeration value 'OpenCLDebugInfo100DebugModuleINTEL' not handled in switch [-Werror=switch]
 2683 |     switch (ext_inst_key) {
```

**Comment by bashbaug** [comment]
I made minimal changes to fix the build.

If these changes aren't ready to merge it would be good to cherry-pick the last commit so other builds don't fail in the future.

**Review by s-perron — APPROVED** [review]

**Pull request merged**
