### PR TITLE
Suppot for SPV_QCOM_image_processing2

### PR DESCRIPTION
**Pull request by wooyoungqcom**

### CODE REVIEW

**Review by alan-baker — COMMENTED** [review]
Looks, please just fix the formatting issues.

**Comment by alan-baker** [comment]
It's still hit a bunch of formatting issues in the tests.

**Comment by wooyoungqcom** [comment]
Fixed the formatting issues in test/val/val_image_test.cpp

**Comment by alan-baker** [comment]
Smoketest is due to older headers.

**Review by alan-baker — APPROVED** [review]

**Pull request merged**
