### PR TITLE
Add spirv-lesspipe.sh

### PR DESCRIPTION
**Pull request by dneto0**
Suggested by @steve-lunarg in issue 359.

### CODE REVIEW

**Comment by dneto0** [comment]
For Windows users, it might be more friendly to add a .sh suffix to lesspipe since executables might only be run via an extension association.

**Comment by steve-lunarg** [comment]
Agreed about the .sh suffix.  That's a common convention in the *nix world anyway, so seems appropriate for both.

Also, though it's a very minor thing, I suppose technically the script could be #!/bin/sh rather than #!/bin/bash, which is a slightly less demanding request.

**Comment by dneto0** [comment]
- Added the .sh suffix
- The script now passes through extra arguments to spirv-dis, so the user can specify things like --raw-id and --no-color options in the LESSOPEN configuration.
- documented the change in CHANGES

Ready for review again.

**Comment by antiagainst** [comment]
+2

**Comment by dneto0** [comment]
Rebased. Keeping +2

**Pull request merged**
