### PR TITLE
Add validation for SPV_EXT_demote_to_helper_invocation

### PR DESCRIPTION
**Pull request by jeffbolznv**
This depends on https://github.com/KhronosGroup/SPIRV-Headers/pull/121 and won't pass CI until that gets merged and I can update DEPS.

### CODE REVIEW

**Comment by jeffbolznv** [comment]
I've updated DEPS to pick up the new spirv-headers. The glslang change got merged already, and picking up spirv-headers makes it not fail validation in one of its self-tests, which causes CI to fail. How am I supposed to resolve this? I don't think I can change either repo without breaking the other one. Do I need to disable the test in glslang?

**Comment by jeffbolznv** [comment]
Oh wait, glslang has its own version of spirv-headers, I think I can just fix it in glslang first.

**Comment by jeffbolznv** [comment]
Removed WIP, I think this is ready.

**Comment by jeffbolznv** [comment]
Added the check for bool.

**Comment by alan-baker** [comment]
Please rebase and fix the formatting.

**Pull request merged**
