### PR TITLE
Add support for SPV_KHR_non_semantic_info

### PR DESCRIPTION
**Pull request by baldurk**

### CODE REVIEW

**Comment by dneto0** [comment]
Hey @afd the build failures here seem to be an overrides warning for protobufs code (see below).  That's unrelated to this PR.  Please take a look.


[190/885] Building CXX object external/protobuf/cmake/CMakeFiles/libprotobuf.dir/__/src/google/protobuf/util/internal/default_value_objectwriter.cc.o
In file included from ../external/protobuf/src/google/protobuf/util/internal/default_value_objectwriter.cc:31:
../external/protobuf/src/google/protobuf/util/internal/default_value_objectwriter.h:122:37: warning: 'RenderNull' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  virtual DefaultValueObjectWriter* RenderNull(StringPiece name);
                                    ^
../external/protobuf/src/google/protobuf/util/internal/object_writer.h:105:25: note: overridden virtual function is here
  virtual ObjectWriter* RenderNull(StringPiece name) = 0;

**Comment by dneto0** [comment]
Looks like there are some legit endogenous issues.
E.g. GCC release build has these errors:

867/889] Building CXX object test/val/CMakeFiles/test_val_fghijklmnop.dir/val_non_semantic_test.cpp.o
FAILED: test/val/CMakeFiles/test_val_fghijklmnop.dir/val_non_semantic_test.cpp.o
/usr/bin/c++   -DSPIRV_CHECK_CONTEXT -DSPIRV_COLOR_TERMINAL -DSPIRV_LINUX -DSPIRV_TIMER_ENABLED -I../ -I../external/spirv-headers/include -I../include -I../test -I. -isystem ../external/googletest/googletest/include -isystem ../external/googletest/googlemock/include -I../external/effcee -I../external/effcee/effcee/.. -I../external/re2 -isystem ../external/googletest/googlemock -isystem ../external/googletest/googletest -O2 -g -DNDEBUG -fPIE   -Wall -Wextra -Wnon-virtual-dtor -Wno-missing-field-initializers -Werror -std=c++11 -fno-exceptions -fno-rtti -Wno-long-long -Wshadow -Wundef -Wconversion -Wno-sign-conversion -Wno-undef -Wno-shadow -std=gnu++11 -MD -MT test/val/CMakeFiles/test_val_fghijklmnop.dir/val_non_semantic_test.cpp.o -MF test/val/CMakeFiles/test_val_fghijklmnop.dir/val_non_semantic_test.cpp.o.d -o test/val/CMakeFiles/test_val_fghijklmnop.dir/val_non_semantic_test.cpp.o -c /tmpfs/src/github/SPIRV-Tools/test/val/val_non_semantic_test.cpp
/tmpfs/src/github/SPIRV-Tools/test/val/val_non_semantic_test.cpp:128:69: error: unterminated raw string
                          Combine(Values(true), Values(true), Values(R"(
                                                                     ^
/tmpfs/src/github/SPIRV-Tools/test/val/val_non_semantic_test.cpp:129:74: error: missing terminating " character [-Werror]
 %result = OpExtInst %void %extinst  123 %i32 %u32_2 %f32vec4_1234 %u32_0)"),
                                                                          ^
/tmpfs/src/github/SPIRV-Tools/test/val/val_non_semantic_test.cpp:127:1: error: stray ‘R’ in program
 INSTANTIATE_TEST_SUITE_P(ComplexGlobalExtInst, ValidateNonSemanticGenerated,
 ^
/tmpfs/src/github/SPIRV-Tools/test/val/val_non_semantic_test.cpp:127:1: error: missing terminating " character
/tmpfs/src/github/SPIRV-Tools/test/val/val_non_semantic_test.cpp:127:1: error: stray ‘R’ in program
/tmpfs/src/github/SPIRV-Tools/test/val/val_non_semantic_test.cpp:127:1: error: missing terminating " character
/tmpfs/src/github/SPIRV-Tools/test/val/val_non_semantic_test.cpp:50:15: error: unused parameter ‘env’ [-Werror=unused-parameter]
 CodeGenerator GetNonSemanticCodeGenerator(spv_target_env env,

**Comment by dneto0** [comment]
Hm. That raw string issue might be an bad interaction with googletest.  I've seen that before.  Should be easy for me to fix.

**Comment by dneto0** [comment]
It's also a pretty old GCC.  GNU 4.8.5

**Comment by baldurk** [comment]
Is there anything you want me to fixup on the branch? That raw string could probably be regular literal, I think I deleted the second line I had that prompted it to be a raw literal.

**Comment by dneto0** [comment]
> Is there anything you want me to fixup on the branch? That raw string could probably be regular literal, I think I deleted the second line I had that prompted it to be a raw literal. 

Not just yet.
I'm experimenting with some patches on another PR #3110 
I have a few more hours to try.

**Comment by dneto0** [comment]
This content was merged via #3110

**Pull request closed without merging**
