### PR TITLE
Add Vulkan-specific validation rules for atomics

### PR DESCRIPTION
**Pull request by atgoo**
Added atomic instructions validation rules from
https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#spirvenv-module-validation

### CODE REVIEW

**Comment by atgoo** [comment]
Fails Vulkan CTS master. Looking into this now.

**Comment by atgoo** [comment]
Disabled the check which fails Vulkan CTS.

**Comment by dneto0** [comment]
I filed https://github.com/KhronosGroup/SPIRV-Tools/issues/1278 to re-enable the check that was disabled, and to track the CTS change in flight to fix it.

**Comment by dneto0** [comment]
Rebased and pushed into master as a61e4c13562
I didn't squash this time because I want to keep separate the commit that disables the check, so it can more easily be reversed.

**Pull request closed without merging**
