### PR TITLE
spirv-val: Add Vulkan Image Format check

### PR DESCRIPTION
**Pull request by sfricke-samsung**
Adds `VUID-StandaloneSpirv-Image-04965`

### CODE REVIEW

**Comment by sfricke-samsung** [comment]
So [hlsl_format_rwtexture_frag](https://github.com/KhronosGroup/glslang/blob/master/Test/hlsl.format.rwtexture.frag) is [producing](https://github.com/KhronosGroup/glslang/blob/master/Test/baseResults/hlsl.format.rwtexture.frag.out) bad SPIR-V images mixing floats and int types

Happy to put work to fix things, but what is the procedure for this, do I just try and make a fix in `glslang` and then rebase this when new version is rolled in?

**Review by alan-baker — COMMENTED** [review]
Sorry for the delay, I'm trying to dig through the history on this one.

**Comment by alan-baker** [comment]
I'm confused how this reconciles with https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#spirvenv-image-signedness. This VU has been around for a long time in some form (pre-dating the image operands).

**Comment by alan-baker** [comment]
As for the glslang failure, we can land the improved validation when it is settled and then fix glslang.

**Comment by s-perron** [comment]
This PR is stale, so I will close it. Open a new PR if needed.

**Pull request closed without merging**
