### PR TITLE
Rename endian.h to spirv_endian.h

### PR DESCRIPTION
**Pull request by dneto0**
If we later add a source/ as an -I include directory,
then avoid confusing other headers that want to include the
standard "endian.h" from /usr/include.

### CODE REVIEW

**Comment by umar456** [comment]
LGTM

**Comment by dekimir** [comment]
+2

**Comment by antiagainst** [comment]
It seems `endian.cpp` is not reamed as `spirv_endian.cpp`?

**Comment by dneto0** [comment]
New version also moves source/endian.cpp to source/spirv_endian.cpp.

**Comment by antiagainst** [comment]
LGTM

**Pull request merged**
