### PR TITLE
LocalMultiStoreElim: Support OpVariable Initialization

### PR DESCRIPTION
**Pull request by greg-lunarg**
Treat an OpVariable with initialization as if it was an OpStore.
With PR #1073, this completes work for issue #1017.

### CODE REVIEW

**Comment by s-perron** [comment]
I'll merge once the formatting has been fixed.

**Comment by greg-lunarg** [comment]
Not sure of the cause of the current failure. Anybody have an idea?

**Comment by s-perron** [comment]
I don't think the error is related to your change.  It is related to effcee, and the Windows debug build.  @alan-baker had told me something about that.  I think you change should be good.  I'll double check and get back to you on Monday.

**Comment by s-perron** [comment]
rebase, squashed, and merged as 78c025ab.

**Pull request closed without merging**
