### PR TITLE
Fixing instances of iteration over unordered containers

### PR DESCRIPTION
**Pull request by alan-baker**
* There were several instances found in the validator
 * validate_id.cpp
 * validate_decorations.cpp
 * validate_interfaces.cpp

### CODE REVIEW

**Comment by alan-baker** [comment]
@johnkslang can you check if this fixes your problems?

**Comment by dneto0** [comment]
Addresses part of #1863

**Comment by alan-baker** [comment]
Rebased and submitted as 6d27a8350fbc339909834a6ef339c805cb1ab69b

**Comment by johnkslang** [comment]
Verified. The platform differences are now gone.

Thanks!

**Pull request closed without merging**
