### PR TITLE
Fixes https://github.com/KhronosGroup/SPIRV-Tools/issues/2997

### PR DESCRIPTION
**Pull request by Tobski**
Also validates the type parameters of Result Type and Value for
OpGroupNonUniformBroadcast, BroadcastFirst, and QuadBroadcast

### CODE REVIEW

**Comment by Tobski** [comment]
Note for reviewers: spir-v tools don't yet support SPIR-V 1.5, so I couldn't figure out a (non-hacky) way to write a test to check the behaviour under 1.5 semantics (i.e. that constants aren't required). It seems to work, but I can't write tests for the 1.5 portion until that support lands. It wasn't clear to me if I should even handle the 1.5 semantics in the validation code because of this, so I put it into a separate commit.

**Comment by alan-baker** [comment]
SPIRV-Tools does support SPIR-V 1.5 as of 5a48c0da15628d69b176f152fcddb1d67661f61e (Sept 13). Validation tests can be written by compiling and validating using the SPV_ENV_UNVERSAL_1_5 target environment. There are tests in test/val/val_capability_tests.cpp that use it.

**Comment by Tobski** [comment]
That's weird... it didn't show up anywhere when I tried to use it, checked for that exact environment variable, in fact. I definitely fetched the latest head too 🤔 

Something screwy probably going on with my local repo, I'll grab it fresh again and see what happens.

**Comment by s-perron** [comment]
@Tobski Is this still being worked on?

**Comment by s-perron** [comment]
This seems to be stale.  I'll close it.  Reopen if it is still being worked on.

**Pull request closed without merging**
