### PR TITLE
Fix handling of OpPhi in convert-relaxed-to-half

### LINKED ISSUE #4452: spirv-opt error: OpPhi must appear within a non-entry block before all non-OpPhi instructions
Optimizing for performance and then running the `--convert-relaxed-to-half` pass generates invalid SPIR-V.

I attached a [test.frag.txt](https://github.com/KhronosGroup/SPIRV-Tools/files/6941712/test.frag.txt) program that reproduces the issue. Repro steps:

```
mv test.frag.txt test.frag

# Compile.
glslangValidator -V -o test.unoptimized.spv test.frag

# Optimize for performance.
spirv-opt -O test.unoptimized.spv -o test.optimized.spv

# Check that it's good so far.
spirv-val test.optimized.spv

# Convert relaxed to half.
spirv-opt \
    --convert-relaxed-to-half \
    --simplify-instructions \
    --redundancy-elimination \
    --eliminate-dead-code-aggressive \
    test.optimized.spv \
    -o test.half.spv

# Validate the SPIR-V.
# This outputs:
# error: line 54: OpPhi must appear within a non-entry block before all non-OpPhi instructions (except for OpLine, which can be mixed with OpPhi).
spirv-val test.half.spv
```

```
# glslangValidator --version
# Glslang Version: 10:11.5.0
# ESSL Version: OpenGL ES GLSL 3.20 glslang Khronos. 11.5.0
# GLSL Version: 4.60 glslang Khronos. 11.5.0
# SPIR-V Version 0x00010500, Revision 4
# GLSL.std.450 Version 100, Revision 1
# Khronos Tool ID 8
# SPIR-V Generator Version 10
# GL_KHR_vulkan_glsl version 100
# ARB_GL_gl_spirv version 100

# spirv-opt --version
# SPIRV-Tools v2021.3-dev v1.3.0-2585-gf6b2a4b38
```

### PR DESCRIPTION
**Pull request by greg-lunarg**
Fixes #4452

### CODE REVIEW

**Comment by greg-lunarg** [comment]
@s-perron Please review

**Review by s-perron — CHANGES_REQUESTED** [review]
LGTM, just needs a test.

**Comment by greg-lunarg** [comment]
Test added

**Review by s-perron — APPROVED** [review]

**Comment by greg-lunarg** [comment]
The shaderc smoketest failures appear to be due to the previous PR which fixed some decoration validation. These test are failing because their generated SPIR-V is now failing validation. But these failures are unrelated to this PR which is isolated to the --convert-relaxed-to-half which is an isolated pass not being applied to these tests. So I think it is safe to merge this PR.

I will look at the smoke tests that are failing. They appear to be failing due to SPIR-V generated by glslangValidator. One way or the other, these will need to be fixed.

**Pull request merged**
