### PR TITLE
reflect debug

### PR DESCRIPTION
**Pull request by s-perron**
- Rename strip reflect to strip nonsemantic
- Don't remove debug info in strip-nonsemantic

### CODE REVIEW

**Review by dneto0 — CHANGES_REQUESTED** [review]
There should still be a way to remove the rich debug info that uses non-semantic instructions.
I'm concerned that flows use the strip-non-semantic-info pass to be able to pass a module into an older driver that doesn't know about the NonSemantic.* convention.  And I think  this change will break those flows.

**Comment by dneto0** [comment]
>  I'm concerned that flows use the strip-non-semantic-info pass to be able to pass a module into an older driver that doesn't know about the NonSemantic.* convention. And I think this change will break those flows.

Is there a use case for stripping non-semantic instructions *except* for the rich debug info?  The point about a driver understanding non-semantic instructions is it can ignore anything in that class that it doesn't understand.

**Comment by s-perron** [comment]
> There should still be a way to remove the rich debug info that uses non-semantic instructions.

I'm try to write a test, but I would expect those to be removed if they are extended instructions where the extended instruction set starts with "NonSemantic" (or whatever it is suppose to be).  The code that is there remains the same.  This will leave debug instruction that are not part of a NonSemantic instruction set.

We should try to have a test for what you want to make sure it works.

**Comment by dneto0** [comment]
> > There should still be a way to remove the rich debug info that uses non-semantic instructions.
> 
> I'm try to write a test, but I would expect those to be removed if they are extended instructions where the extended instruction set starts with "NonSemantic" (or whatever it is suppose to be). The code that is there remains the same. This will leave debug instruction that are not part of a NonSemantic instruction set.

Oh, I see.  The point is that "don't remove debug info" means don't remove the instructions from SPIR-V's "Debug instructions" section.  I was getting confused between that and the rich debug info encoded as NonSemantic instructions.  Sounds good to me! My confusion.

> 
> We should try to have a test for what you want to make sure it works.

**Review by dneto0 — APPROVED** [review]
The second commit LGTM, now that I understand the goal correctly.  :-)
Please submit only after #4661 has landed.

**Comment by s-perron** [comment]
#4661 has landed. I have  rebased, and I will merge if the tests pass.

**Pull request merged**
