### PR TITLE
Let symbol export tests respect SPIRV_SKIP_TESTS

### PR DESCRIPTION
**Pull request by antiagainst**

### CODE REVIEW

**Comment by antiagainst** [comment]
Somehow Kokoro decided to jump in and throw hates on my pull request. Appveyor and Travis are giving green lights to this one, though.

**Comment by ehsannas** [comment]
This is because #1625 is not merged yet. The backend kokoro triggers a run, but i won't find the kokoro build scripts in the repo.

**Comment by antiagainst** [comment]
I see. Thanks!

**Comment by antiagainst** [comment]
Trivial enough. I'll just submit this one.

**Pull request merged**
