### PR TITLE
spirv-diff: Leave undefined ids unpaired.

### LINKED ISSUE #5260: spirv-diff reports differences between a file and itself
When passed the attached file as both the "source" and "destination" for the diff, `spirv-diff` prints:

```
 ; SPIR-V
 ; Version: 1.6
 ; Generator: Khronos SPIR-V Tools Assembler; 0
-; Bound: 546
+; Bound: 547
 ; Schema: 0
                OpCapability SampledCubeArray
                OpCapability ImageQuery
                OpCapability Image1D
                OpCapability Shader
...
```

and then reports no other changes in the file. It should report no changes.

[identical.zip](https://github.com/KhronosGroup/SPIRV-Tools/files/11672639/identical.zip)

### PR DESCRIPTION
**Pull request by jimblandy**
If an id in one module is not defined by any instruction, don't bother matching it with an id in the other module, as this disturbs the reported id bound, resulting in spurious differences.

Fixes #5260.

### CODE REVIEW

**Review by ShabbyX — DISMISSED** [review]
:+1:

**Review by ShabbyX — APPROVED** [review]

**Comment by ShabbyX** [comment]
@jimblandy the PR needs a `clang-format`

**Comment by jimblandy** [comment]
> @jimblandy the PR needs a clang-format

D'oh!

**Review by ShabbyX — APPROVED** [review]

**Comment by s-perron** [comment]
The continuous builds are failing because of this: https://github.com/KhronosGroup/SPIRV-Tools/commit/ae1843b67c54d5f813779e17613cb8750da953f5

Click on the red x in near the top  on the left.

**Comment by s-perron** [comment]
```
[ RUN      ] DiffTest.RayQueryTypes
/tmpfs/src/github/SPIRV-Tools/test/diff/diff_test_utils.cpp:54: Failure
Expected equality of these values:
  diff_result.str()
    Which is: " ; SPIR-V\n ; Version: 1.6\n ; Generator: Khronos SPIR-V Tools Assembler; 0\n ; Bound: 45\n ; Schema: 0\n OpCapability RayQueryKHR\n OpCapability Shader\n OpExtension \"SPV_KHR_ray_query\"\n OpMemoryModel Logical GLSL450\n OpEntryPoint GLCompute %43 \"main\"\n OpExecutionMode %43 LocalSize 1 1 1\n %2 = OpTypeVoid\n %3 = OpTypeAccelerationStructureKHR\n %13 = OpTypeRayQueryKHR\n %44 = OpTypeFunction %2\n %43 = OpFunction %2 None %44\n %42 = OpLabel\n OpReturn\n OpFunctionEnd\n"
  expected_diff
    Which is: " ; SPIR-V\n ; Version: 1.6\n ; Generator: Khronos SPIR-V Tools Assembler; 0\n-; Bound: 45\n+; Bound: 83\n ; Schema: 0\n OpCapability RayQueryKHR\n OpCapability Shader\n OpExtension \"SPV_KHR_ray_query\"\n OpMemoryModel Logical GLSL450\n OpEntryPoint GLCompute %43 \"main\"\n OpExecutionMode %43 LocalSize 1 1 1\n %2 = OpTypeVoid\n %3 = OpTypeAccelerationStructureKHR\n %13 = OpTypeRayQueryKHR\n %44 = OpTypeFunction %2\n %43 = OpFunction %2 None %44\n %42 = OpLabel\n OpReturn\n OpFunctionEnd\n"
With diff:
@@ -2,5 +2,6 @@
  ; Version: 1.6
  ; Generator: Khronos SPIR-V Tools Assembler; 0
- ; Bound: 45
+-; Bound: 45
++; Bound: 83
  ; Schema: 0
  OpCapability RayQueryKHR


[  FAILED  ] DiffTest.RayQueryTypes (0 ms)
[ RUN      ] DiffTest.RayQueryTypesNoDebug
/tmpfs/src/github/SPIRV-Tools/test/diff/diff_test_utils.cpp:54: Failure
Expected equality of these values:
  diff_result.str()
    Which is: " ; SPIR-V\n ; Version: 1.6\n ; Generator: Khronos SPIR-V Tools Assembler; 0\n ; Bound: 45\n ; Schema: 0\n OpCapability RayQueryKHR\n OpCapability Shader\n OpExtension \"SPV_KHR_ray_query\"\n OpMemoryModel Logical GLSL450\n OpEntryPoint GLCompute %43 \"main\"\n OpExecutionMode %43 LocalSize 1 1 1\n %2 = OpTypeVoid\n %3 = OpTypeAccelerationStructureKHR\n %13 = OpTypeRayQueryKHR\n %44 = OpTypeFunction %2\n %43 = OpFunction %2 None %44\n %42 = OpLabel\n OpReturn\n OpFunctionEnd\n"
  expected_diff
    Which is: " ; SPIR-V\n ; Version: 1.6\n ; Generator: Khronos SPIR-V Tools Assembler; 0\n-; Bound: 45\n+; Bound: 83\n ; Schema: 0\n OpCapability RayQueryKHR\n OpCapability Shader\n OpExtension \"SPV_KHR_ray_query\"\n OpMemoryModel Logical GLSL450\n OpEntryPoint GLCompute %43 \"main\"\n OpExecutionMode %43 LocalSize 1 1 1\n %2 = OpTypeVoid\n %3 = OpTypeAccelerationStructureKHR\n %13 = OpTypeRayQueryKHR\n %44 = OpTypeFunction %2\n %43 = OpFunction %2 None %44\n %42 = OpLabel\n OpReturn\n OpFunctionEnd\n"
With diff:
@@ -2,5 +2,6 @@
  ; Version: 1.6
  ; Generator: Khronos SPIR-V Tools Assembler; 0
- ; Bound: 45
+-; Bound: 45
++; Bound: 83
  ; Schema: 0
  OpCapability RayQueryKHR
```

**Comment by s-perron** [comment]
If we cannot get a quick fix, please revert.

**Comment by ShabbyX** [comment]
Fixing here: https://github.com/KhronosGroup/SPIRV-Tools/pull/5264

**Pull request merged**
