### PR TITLE
Switch SPIRV-Tools to use spirv.hpp11 internally

### LINKED ISSUE #4960: OSS-Fuzz: Enum Invalid-enum-value
In `spirv-val` there is a lot of usage of `GetOperandAs` which does a `static_cast` to the enum based on a value read from the binary. Doing a `static_cast` to a value which is not in the enum is undefined.

This casting happens all over the place in spirv-val.

Either we need to create wrapper functions using a switch to only convert values which are actually in the enum or we can disable the sanitizer with something like https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html#disabling-instrumentation-with-attribute-no-sanitize-undefined.

See https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=42610

### PR DESCRIPTION
**Pull request by alan-baker**
Fixes #4960

* Switches to using enum classes with an underlying type to avoid undefined behaviour

### CODE REVIEW

**Comment by alan-baker** [comment]
This will require https://github.com/KhronosGroup/SPIRV-Headers/pull/301 to make the GN build work.

**Review by dnovillo — APPROVED** [review]
It's a bit mind numbing going through the changes, but they look fine to me.  The spirv C headers are completely disabled here, by means of the build file definitions, right?

**Comment by alan-baker** [comment]
The C headers are definitely disabled in Bazel builds, but it's harder to do in CMake or GN. Bazel found all the extra instances that the C header was included unnecessarily.

**Comment by dneto0** [comment]
I'm testing this along with a rollback of the SPIRV-Headers change.
(Becuase GN doesn't recognize .hpp11 files)

**Review by dneto0 — APPROVED** [review]
Thank you!

**Pull request merged**
