### PR TITLE
Support building under CYGWIN

### PR DESCRIPTION
**Pull request by dneto0**
- Parse CHANGES file with Universal Python line endings in case
  the source tree was checked out with Windows line endings.
- Use our own clone of strnlen_s which might not be available
  everywhere.

Fixes https://github.com/KhronosGroup/SPIRV-Tools/issues/508

### CODE REVIEW

**Comment by antiagainst** [comment]
LGTM, just need to let the bot happy.

If we are gonna support CYGWIN, would be nice to add appeyvor config for it.

**Comment by dneto0** [comment]
Added a commit to fix the signed/unsigned compare issue.  I'll keep the LGTM otherwise.

I added https://github.com/KhronosGroup/SPIRV-Tools/projects/2#card-1161778 for bot support.

**Comment by dneto0** [comment]
Rebased

**Comment by dneto0** [comment]
Squashed

**Comment by dneto0** [comment]
Rebased

**Pull request merged**
