### PR TITLE
Add validation for SPV_EXT_shader_atomic_float16_add

### PR DESCRIPTION
**Pull request by jekstrand**

### CODE REVIEW

**Comment by alan-baker** [comment]
@jekstrand Please update and force push to pick up the new headers.

**Comment by jekstrand** [comment]
Done.

**Comment by alan-baker** [comment]
It looks like this will need to be rebased on top of the integer dot product support when that is merged.

**Comment by alan-baker** [comment]
@jekstrand please rebase on master.

**Comment by jekstrand** [comment]
Done.

**Comment by alan-baker** [comment]
Looks like a unit test, `ValidateAtomics.AtomicAddFloat16VulkanSuccess` is failing.

**Comment by jekstrand** [comment]
Fixed.

**Pull request merged**
