### PR TITLE
 DefUseManager: rename comparison operators to 'CompareAndPrintDifferences'

### PR DESCRIPTION
**Pull request by Ace17**

### CODE REVIEW

**Review by s-perron — CHANGES_REQUESTED** [review]
This code is there for debugging purposes.  This check is only done on in an assert that the def use manager is consistent.  We rebuild it from scratch and then make sure it matches the saved one.  We do all of this extra checking so that if it fails we can put a break point on all of the return statements to see exactly what is different.

We do not add debugging output because we want to act like a proper equality operator.

If you have reasons other than just a clean up, then let me know what they are.  We could probably do something different if there is a good reason, but I do not want to lose the debugability.

**Comment by Ace17** [comment]
OK, so if I understand correctly, this function is only needed for debugging purposes.

Have you considered adding print statements, and renaming this function to something like "CompareAndPrintDifferences" ?
( It seems like here, there are no use-cases where the semantics of `operator==` are needed ).

What do you think?

**Comment by Ace17** [comment]
> If you have reasons other than just a clean up, then let me know what they are.

This PR is a preliminary cleanup.

I have a use-case where's there's a *huge* performance gap between the linux version (1min30) and the windows version (12min). The profilers have shown that it's related to memory allocations.

So I want to do some performance-oriented rethinking about how the containers are used in this class. 
Of course, every usage of these containers will add friction to this work.
This is why I was cleaning this up.

**Comment by s-perron** [comment]
> Have you considered adding print statements, and renaming this function to something like "CompareAndPrintDifferences" ?

Yes that is the alternative I was thinking of.  If you want to do that, I will definitely approve it.

**Comment by Ace17** [comment]
Ok, I started working on this renaming, but I couldn't find any callers for `operator==`.

Seems like this function is actually dead, as I am able to do a full build + ctest after deleting this function.

> This check is only done on in an assert that the def use manager is consistent.

Could you please tell me where this assertion is?

Thanks !

**Comment by s-perron** [comment]
I should get called from here: https://github.com/KhronosGroup/SPIRV-Tools/blob/1ed847f43804efaac09e67ebdd86783d801f7b62/source/opt/ir_context.cpp#L320

**Comment by Ace17** [comment]
Here it is.

I took the liberty of slightly alltering the control flow, in order to print all the differences (instead of only the first one) ; this might be handy in a debugging context.

**Review by s-perron — APPROVED** [review]

**Pull request merged**
