### PR TITLE
BUILD.gn: Don't warn on unreachable code

### PR DESCRIPTION
**Pull request by Kangz**

### CODE REVIEW

**Comment by s-perron** [comment]
Could we get more background on this? I don't like the idea of turning off warnings.  We don't have this options in any of our other build files, as far as I know.  What code is triggering this warning?

**Comment by Kangz** [comment]
This happens when trying to upgrade the compiler and other build dependencies of Dawn in this [CL](https://dawn-review.googlesource.com/c/dawn/+/19601).

The error messages are the following:
```
[544/776] CXX obj/third_party/SPIRV-Tools/spvtools_opt/ir_context.o
FAILED: obj/third_party/SPIRV-Tools/spvtools_opt/ir_context.o 
/b/s/w/ir/cache/goma/client/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/third_party/SPIRV-Tools/spvtools_opt/ir_context.o.d -DUSE_UDEV -DUSE_AURA=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_X11=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_GNU_SOURCE -DCR_CLANG_REVISION=\"n346557-4e0d9925-2\" -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -D_LIBCPP_ABI_UNSTABLE -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCXXABI_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCPP_ENABLE_NODISCARD -DCR_LIBCXX_REVISION=375504 -DCR_SYSROOT_HASH=79a7783607a69b6f439add567eb6fcb48877085c -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -I../.. -Igen -I../../third_party/SPIRV-Tools -Igen/third_party/SPIRV-Tools -I../../third_party/spirv-headers/include -I../../third_party/SPIRV-Tools/include -I../../third_party/SPIRV-Tools/include -I../../third_party/spirv-headers/include -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -funwind-tables -fPIC -B../../third_party/binutils/Linux_x64/Release/bin -pthread -fcolor-diagnostics -fmerge-all-constants -fcrash-diagnostics-dir=../../tools/clang/crashreports -Xclang -mllvm -Xclang -instcombine-lower-dbg-declare=0 -fcomplete-member-pointers -m64 -march=x86-64 -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -Xclang -fdebug-compilation-dir -Xclang . -no-canonical-prefixes -Wall -Werror -Wextra -Wimplicit-fallthrough -Wunreachable-code -Wthread-safety -Wextra-semi -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-unneeded-internal-declaration -Wno-undefined-var-template -Wno-ignored-pragma-optimize -Wno-implicit-int-float-conversion -Wno-final-dtor-non-final-class -Wno-builtin-assume-aligned-alignment -Wno-deprecated-copy -Wno-non-c-typedef-for-linkage -Wno-pointer-to-int-cast -O2 -fno-ident -fdata-sections -ffunction-sections -fno-omit-frame-pointer -g0 -ftrivial-auto-var-init=pattern -fvisibility=hidden -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -Wno-implicit-fallthrough -Wno-newline-eof -std=c++14 -fno-exceptions -fno-rtti -nostdinc++ -isystem../../buildtools/third_party/libc++/trunk/include -isystem../../buildtools/third_party/libc++abi/trunk/include --sysroot=../../build/linux/debian_sid_amd64-sysroot -fvisibility-inlines-hidden -c ../../third_party/SPIRV-Tools/source/opt/ir_context.cpp -o obj/third_party/SPIRV-Tools/spvtools_opt/ir_context.o
../../third_party/SPIRV-Tools/source/opt/ir_context.cpp:276:7: error: code will never be executed [-Werror,-Wunreachable-code]
  if (AreAnalysesValid(kAnalysisDefUse)) {
      ^~~~~~~~~~~~~~~~
1 error generated.
```

```
[519/776] CXX obj/third_party/SPIRV-Tools/spvtools_opt/graphics_robust_access_pass.o
FAILED: obj/third_party/SPIRV-Tools/spvtools_opt/graphics_robust_access_pass.o 
/b/s/w/ir/cache/goma/client/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/third_party/SPIRV-Tools/spvtools_opt/graphics_robust_access_pass.o.d -DUSE_UDEV -DUSE_AURA=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_X11=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_GNU_SOURCE -DCR_CLANG_REVISION=\"n346557-4e0d9925-2\" -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -D_LIBCPP_ABI_UNSTABLE -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCXXABI_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCPP_ENABLE_NODISCARD -DCR_LIBCXX_REVISION=375504 -DCR_SYSROOT_HASH=79a7783607a69b6f439add567eb6fcb48877085c -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -I../.. -Igen -I../../third_party/SPIRV-Tools -Igen/third_party/SPIRV-Tools -I../../third_party/spirv-headers/include -I../../third_party/SPIRV-Tools/include -I../../third_party/SPIRV-Tools/include -I../../third_party/spirv-headers/include -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -funwind-tables -fPIC -B../../third_party/binutils/Linux_x64/Release/bin -pthread -fcolor-diagnostics -fmerge-all-constants -fcrash-diagnostics-dir=../../tools/clang/crashreports -Xclang -mllvm -Xclang -instcombine-lower-dbg-declare=0 -fcomplete-member-pointers -m64 -march=x86-64 -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -Xclang -fdebug-compilation-dir -Xclang . -no-canonical-prefixes -Wall -Werror -Wextra -Wimplicit-fallthrough -Wunreachable-code -Wthread-safety -Wextra-semi -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-unneeded-internal-declaration -Wno-undefined-var-template -Wno-ignored-pragma-optimize -Wno-implicit-int-float-conversion -Wno-final-dtor-non-final-class -Wno-builtin-assume-aligned-alignment -Wno-deprecated-copy -Wno-non-c-typedef-for-linkage -Wno-pointer-to-int-cast -O2 -fno-ident -fdata-sections -ffunction-sections -fno-omit-frame-pointer -g0 -ftrivial-auto-var-init=pattern -fvisibility=hidden -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -Wno-implicit-fallthrough -Wno-newline-eof -std=c++14 -fno-exceptions -fno-rtti -nostdinc++ -isystem../../buildtools/third_party/libc++/trunk/include -isystem../../buildtools/third_party/libc++abi/trunk/include --sysroot=../../build/linux/debian_sid_amd64-sysroot -fvisibility-inlines-hidden -c ../../third_party/SPIRV-Tools/source/opt/graphics_robust_access_pass.cpp -o obj/third_party/SPIRV-Tools/spvtools_opt/graphics_robust_access_pass.o
../../third_party/SPIRV-Tools/source/opt/graphics_robust_access_pass.cpp:822:23: error: code will never be executed [-Werror,-Wunreachable-code]
  auto* def_use_mgr = context()->get_def_use_mgr();
                      ^~~~~~~
1 error generated.
```

The first issue is an easy fix (using `#else`) but I'm not sure what to do with the second one so I disabled the warning instead. I'd be happy to do a more proper fix, but ideally it doesn't involve removing hundreds of lines of code from `graphics_robust_access_pass.cpp`.

**Comment by s-perron** [comment]
I just merged code that should fix your problem.  I'll close this PR.  If there is still an issue with unreachable code, open a PR that removes it or open an issue that says where it is.

**Comment by Kangz** [comment]
THanks!

**Pull request closed without merging**
