### PR TITLE
Squashed 1 1

### PR DESCRIPTION
**Pull request by dneto0**
This is @dekimir 's work, but squashing away intermediate steps that supported 1.1 with old grammar files.

### CODE REVIEW

**Comment by dneto0** [comment]
+1  
I already reviewed this elsewhere, and my feedback was absorbed.

**Comment by antiagainst** [comment]
Looks good to me.

**Comment by dneto0** [comment]
Addressed feedback from @AWoloszyn

**Comment by antiagainst** [comment]
I'd suggest to squash e26fdc6 & ed1883a. Because in one of them, extinst-1.1 grammar files are introduced but in another they are removed.

**Comment by AWoloszyn** [comment]
Looks good to me once @antiagainst  is happy I am too.

**Comment by antiagainst** [comment]
Sorry, I mean ed1883a & 57b5f96.

**Comment by antiagainst** [comment]
LGTM

**Pull request merged**
