### PR TITLE
Revert "Optimize DefUseManager allocations (#4709)"

### PR DESCRIPTION
**Pull request by greg-lunarg**
This reverts commit d18d0d92e55f44da6af0dc87fb0e3c8034e9a3ac.

This is reverted because it causes a 7X slowdown when legalizing
SPIR-V with NonSemantic.Shader.DebugInfo.100 instructions.
This is due to the creation of very large UseLists for several
heavily used operands for this extension combined with the fact
that this commit changed the performance of Uselists to O(n).

### CODE REVIEW

**Comment by greg-lunarg** [comment]
Yeah, I am seeing an assert in InterfaceVariableScalarReplacementTest.ReplaceInterfaceVarsWithScalars with Debug build.

**Comment by greg-lunarg** [comment]
Regression fixed with #4850

**Comment by greg-lunarg** [comment]
@s-perron PTAL

**Comment by s-perron** [comment]
I'm going on vacation for a week.  @kuhar Can you take a look?

**Comment by kuhar** [comment]
@greg-lunarg would you be able to share an input that exhibits the 7x slowdown (either here or email me in private)? I'd like to step through the code to see what's going on.

**Comment by greg-lunarg** [comment]
@kuhar You will need to get the shader directly from @danginsburg. Dan will contact you to hand you the shader.

The problem originally manifested using dxc which calls spirv-opt to do legalization. Here is the dxc command line to recreate the problem:

`/cygdrive/c/Users/greg/dev/dxc/bin/Release/bin/dxc.exe  -EMainPs -Wno-effects-syntax -T ps_6_0 -fspv-target-env=vulkan1.3 -fspv-debug=vulkan-with-source -spirv -Fo csgo.frag.vdb.fast.spv csgo.frag`

**Comment by greg-lunarg** [comment]
Essentially, the problem is that every NonSemantic.Shader.DebugInfo.100 instruction uses the following operands:

```
%2 = OpExtInstImport "NonSemantic.Shader.DebugInfo.100"
%void = OpTypeVoid
```

For large shaders, there are 1000s of these instructions. When these instructions are added to DefUse, this creates a UseLists of 1000s of entries.

The change that is being reverted changed the representation of UseList in DefUse to use find and insert algorithms of O(n), which caused serious performance degradation for shaders with DebugInfo instructions.


While this is true for OpenCL.DebugInfo.100, it is twice the problem for NonSematic.Shader.DebugInfo.100 since the latter also has its own DebugLine instruction which can double the number of Debug instructions.

**Pull request merged**
