### PR TITLE
Updates to final ray tracing extensions

### PR DESCRIPTION
**Pull request by dgkoch**
Updates to final spec semantics in https://github.com/KhronosGroup/SPIRV-Registry/pull/86

Depends on header updates in https://github.com/KhronosGroup/SPIRV-Headers/pull/182

### CODE REVIEW

**Comment by dgkoch** [comment]
cc @raunraun @johnkslang @dneto0 @alan-baker

**Review by s-perron — APPROVED** [review]

**Comment by dneto0** [comment]
SPIRV-Headers change has been merged.

**Comment by dgkoch** [comment]
SPIRV_headers has been merged now, I'll rebase.

**Comment by dneto0** [comment]
FYI.  Glslang/shaderc parts of the smoketest are expected to fail until https://github.com/KhronosGroup/glslang/pull/2466 is merged

**Comment by s-perron** [comment]
@dgkoch It look like the `base_operand_capabilities_test` are failing.

**Comment by dneto0** [comment]
I might have messed things up here.  I also merged https://github.com/KhronosGroup/SPIRV-Headers/pull/180 to fix a capability depedendency.  That my have caused some capability tests to fail.   I'll see about verifying and fixing.

**Comment by dneto0** [comment]
This support was merged as part of #4028

**Pull request closed without merging**
