### PR TITLE
opt: add GroupNonUniformPartitionedNV capability to trim pass

### PR DESCRIPTION
**Pull request by sudonatalie**

### CODE REVIEW

**Comment by sudonatalie** [comment]
Will be used for the implementation for https://github.com/microsoft/DirectXShaderCompiler/issues/6545

**Review by Keenuts — APPROVED** [review]
Wonder if we need to start thinking about instructions enabled by multiple capabilities. Maybe there is something to do as in "if an capability is core, replace the vendor specific by the core capability"

**Comment by sudonatalie** [comment]
The instructions enabled by this capability aren't and won't be enabled by any others (they have the NV suffix on the instruction too), but that is an optimization I looked into for `SPV_KHR_ray_query` and `SPV_KHR_ray_tracing` in the past, since they implement some of the same instructions and capabilities. It might be worth looking into if we find other examples or the hardware overlap gets more divergent.

**Comment by dneto0** [comment]
> is an optimization I looked into for `SPV_KHR_ray_query` and `SPV_KHR_ray_tracing` in the past, since they implement some of the same instructions and capabilities. It might be worth look

What was the failure mode?  
Once this landed on main, the continuous integration bots failed on mac bazel, due to 60s timeouts, it looks like:

//:opt_fold_test                                                        TIMEOUT in 60.2s
//:val_builtins_test                                                    TIMEOUT in 60.2s

**Comment by sudonatalie** [comment]
@dneto0 The hypothetical optimization of when to apply `SPV_KHR_ray_query` and `SPV_KHR_ray_tracing` is a tangent and not related to this change. 

The only effect of this PR should be that the capability trimming pass now removes `GroupNonUniformPartitionedNV` when it's not needed, so I can't imagine it would cause bot timeouts, but if it does appear to be the culprit please feel free to revert.

**Comment by sudonatalie** [comment]
Oh and the bot failure I saw before rebase was just for an unrelated file's clang-format failure.

**Pull request merged**
