### PR TITLE
AggressiveDCE: Add merge and continue branches for live loop.

### PR DESCRIPTION
**Pull request by greg-lunarg**
This fixes issue #989

### CODE REVIEW

**Comment by greg-lunarg** [comment]
@dneto0 Doh! Forgot the test. It is pretty much the code from #989, but I will add it right now.

**Comment by greg-lunarg** [comment]
Yes, you have indeed surmised the mechanism of the solution. This solution will continue to work when we add the code to do empty loop removal.

**Comment by dneto0** [comment]
Question:  In the example from #989, what happens if the break statement is replaced by an OpReturn or OpKill (if a fragment shader).  Do we need special exceptions for those as well, i.e. add them to the worklist?

**Comment by greg-lunarg** [comment]
Re OpReturn, OpKill: These are not combinators ie are considered to have external effect, and thus are added to the initial worklist. No additional special exceptions are needed.

**Comment by dneto0** [comment]
The bot failure is actually occuring on master, and is unrelated to this change.
I will push this into master.

**Comment by dneto0** [comment]
Rebased and pushed into master as 8dd3d93cf66

**Pull request closed without merging**
