### PR TITLE
Add KHR_ray_query support + ray tracing enums

### PR DESCRIPTION
**Pull request by Tobski**
Based on changes in https://github.com/KhronosGroup/SPIRV-Tools/pull/3233, so that should be accepted first.

### CODE REVIEW

**Comment by s-perron** [comment]
First run of the tests fail because spirv-headers was not updated yet.  I'll try rerunning them.

**Comment by s-perron** [comment]
Still seeing errors related to switches with unhandled cases:

> /tmpfs/src/github/SPIRV-Tools/source/val/validate_scopes.cpp:28:11: error: enumeration value 'SpvScopeShaderCallKHR' not handled in switch [-Werror,-Wswitch]
  switch (static_cast<SpvScope>(scope)) {
          ^

**Comment by dgkoch** [comment]
> Still seeing errors related to switches with unhandled cases:
> 
> > /tmpfs/src/github/SPIRV-Tools/source/val/validate_scopes.cpp:28:11: error: enumeration value 'SpvScopeShaderCallKHR' not handled in switch [-Werror,-Wswitch]
> > switch (static_cast(scope)) {
> > ^

ah. that might be due to my last minute addition..

**Comment by dgkoch** [comment]
trying on #3235

**Comment by dgkoch** [comment]
These changes have been merged via #3235 so this can be closed.

**Pull request closed without merging**
