### PR TITLE
Eliminate parameter-order check from ID validation

### PR DESCRIPTION
**Pull request by dekimir**
Also ensure we don't get thrown off by too many parameters.

### CODE REVIEW

**Comment by dekimir** [comment]
@umar456 PTAL

**Comment by umar456** [comment]
I already perform these checks in the layout pass (see [unit test](https://github.com/KhronosGroup/SPIRV-Tools/pull/96/files#diff-6dc2086e9da925d662089f2876b41bb7L165)). A better approach would be to remove that check from validate_id.

**Comment by dekimir** [comment]
@umar456 The "unit test" link just takes me to this PR's diff :question:

**Comment by umar456** [comment]
Sorry, Here is the link https://github.com/KhronosGroup/SPIRV-Tools/blob/master/test/Validate.Layout.cpp#L165

**Comment by dneto0** [comment]
Functionality looks good to me.
But agree deleting code would be better.  Suggest @dekimir try removing the check from validate_id but keep the tests, possibly adjusting the failure result code if it's different.

**Comment by dekimir** [comment]
Eliminated the check, kept the tests.  The problem with Umar's test is that it doesn't exercise the code in question due to fewer validation bits turned on.  #89 strikes again. :(

**Comment by dneto0** [comment]
+2

**Pull request merged**
