### PR TITLE
Remove source/instruction.cpp

### PR DESCRIPTION
**Pull request by dneto0**
Avoids linker problems on Windows and OSX with duplicate object file
names.  Avoids collision with source/val/instruction.cpp

Fixes https://github.com/KhronosGroup/SPIRV-Tools/issues/451

### CODE REVIEW

**Comment by dneto0** [comment]
FYI https://github.com/google/shaderc would require an update to react to this change.

**Comment by antiagainst** [comment]
It seems `source/instruction.cpp` is not actually removed from git?

**Comment by dneto0** [comment]
Right.  Fixed. :-)

**Comment by dneto0** [comment]
Rebased

**Comment by dneto0** [comment]
squashed

**Pull request merged**
