### PR TITLE
spirv-fuzz: Respect control flow rules when merging returns

### LINKED ISSUE #4278: spirv-fuzz: Merging of returns leads to an invalid CFG
See https://github.com/KhronosGroup/SPIRV-Tools/pull/4277#issuecomment-839082829 for details.

### PR DESCRIPTION
**Pull request by afd**
Fixes #4278.

Some minor code cleanup is incorporated.

### CODE REVIEW

**Comment by afd** [comment]
@stefanomil For interest: I adapted this transformation to use an unreachable block as the continue target. It turns out that using the header as its own continue target doesn't work in general; the validator has been improved and now picks this up as invalid when it didn't previously.

**Comment by afd** [comment]
@alan-baker I can't work out why the format check has failed. I always run the check locally and it passes for me - I'm using the version of clang-format that is used by the CI. Are there any known problems with the format check at present?

**Comment by alan-baker** [comment]
It happened before to me. I just manually apply the diff format checker wants.

**Comment by afd** [comment]
I'll do that. But I'm worried it means that everyone's local format checkers will fail.

**Comment by dneto0** [comment]
>  But I'm worried it means that everyone's local format checkers will fail.

Unexplained reformats have been happening to me too.  It is worrisome but so far the second problem hasn't been triggered. I wonder if there is some hysteresis.

**Pull request merged**
