### PR TITLE
Validator checks OpReturn called from void func

### PR DESCRIPTION
**Pull request by atgoo**
Added check into validate_cfg which checks that OpReturn is not called
from functions which are supposed to return a value.

### CODE REVIEW

**Comment by atgoo** [comment]
Vulkan CTS master passes with this change.

**Comment by dneto0** [comment]
I also filed https://github.com/KhronosGroup/SPIRV-Tools/issues/876 for the opposite condition: OpReturnValue result type must match the function's return type.

**Comment by dneto0** [comment]
Waiting for bots to go green

**Comment by dneto0** [comment]
Rebased, squashed, and pushed into master as  b54997e6ebd9

**Pull request closed without merging**
