### PR TITLE
Fix infinite loop in validation

### PR DESCRIPTION
**Pull request by alan-baker**
Fixes https://crbug.com/38548

* Fixes an issue in structured exit checking where an invalid merge
  could result in an infinite traversal

### CODE REVIEW

**Review by dneto0 — APPROVED** [review]
This is subtle.

**Comment by dneto0** [comment]
The ubsan failure looks unrelated.  Something is using a deprecated clang option?

**Comment by dneto0** [comment]
Ah, the UBSAN flow is new: #4512

**Comment by afd** [comment]
I have fixed the issues with the UBSan configuration, so if you pull and rebase that check should now pass.

**Comment by afd** [comment]
(Or just merge on the basis that we know the UBSan config failure isn't related.)

**Pull request merged**
