### PR TITLE
Add preserver-interface option to spirv-opt

### LINKED ISSUE #5522: Add CLI option to set CreateAggressiveDCEPass(true)
The change broke our HLSL codegen where preserve_interface on this is hardcoded to false.   There is no CLI option to alter this.   More details here:

https://github.com/KhronosGroup/Vulkan-Docs/issues/666

We'd like to move to tools past this change back in 2021.  Stripping inputs from the entry function may work fine for Vulkan spirv.  For transpiling to HLSL, this change broke our PS4 shader pipeline which uses spirv-opt to eliminate various fields.  spirv-opt has no idea that optimized spirv will be transpiled to HLSL to set the flag to true on it's ADCE passes.   Also, the input gaps formed by this aren't handled by the HLSL/PSSL compilers that we use.  Please add a command line option to restore the original behavior. 

This preserves the entry-point interfaces and variables.
--eliminate-dead-code-aggressive-hlsl 

Adds CreateAggressiveDCEPass(true)

I found someone that added a flag to pass the preserve_interface flag across the optimize and legalize options, but then never seemed to bother setting it to true.  Alternatively a flag could set preserve_interfaces to true across all uses.

https://github.com/KhronosGroup/SPIRV-Tools/pull/5268

We just run the tools out of the Vulkan SDK, we don't call APIs or build from source.  So we need a command line option to get the old behavior.  This had to break Roblox code too, so I don't see how this ended up in the main codebase.

### PR DESCRIPTION
**Pull request by s-perron**
The optimizer is able to preserve the interface variables of the
shaders, but that feature has not been exposed to the command line
tool.

This commit adds an option `--preserve-interface` to spirv-opt that will
cause all calls to ADCE to leave the input and output variables, even if
the variable is unused. It will apply regardless of where the option
appears on the command line.

Fixes #5522

### CODE REVIEW

**Comment by s-perron** [comment]
@alecazam Let me now if this fixes your problem. I'm still trying to get input to make sure this is the right direction. To me it seems the most intuitive.

**Comment by alecazam** [comment]
That looks like it would work.  To minimize code churn, could it be a member of the Optimizer class, and then you could just pull it from that.  It would default to false if not set for Vulkan spirv codegen. Then you don't need the split of functions.

**Comment by s-perron** [comment]
I did it this way so I don't have to create another pass over the flags. If it is in the library then `-O --preserve-interface` would not preserve the interface. I could make it work, but I would have to traverse all of the flags once to look for the new flag. This would be a lot more string compares.

**Review by sudonatalie — APPROVED** [review]
Looks good to me!

**Pull request merged**
