### PR TITLE
Eliminate kCapabilitiesMin/Max.

### PR DESCRIPTION
**Pull request by dekimir**
Turn module_capabilities_ into a spv_capability_mask_t.

@antiagainst @AWoloszyn @dneto0 @Qining PTAL.

### CODE REVIEW

**Comment by antiagainst** [comment]
+1

**Comment by dneto0** [comment]
+2

**Comment by Qining** [comment]
So I guess we won't have more than 64 capabilities?

**Comment by dekimir** [comment]
@Qining: I'm sure one day we'll have more than 64, but we decided to keep it simple for now (supporting different SPIR-V versions) and react to the limit busting in the future when it occurs.

**Pull request merged**
