### PR TITLE
Change HasOnlySupportedRefs to consider OpCopyObject

### PR DESCRIPTION
**Pull request by antiagainst**

### CODE REVIEW

**Comment by antiagainst** [comment]
@greg-lunarg: Hey Greg, I'd appreciate if you can take a look at the second commit to make sure everything is fine. :)

**Comment by greg-lunarg** [comment]
Thanks. Looking...

**Comment by greg-lunarg** [comment]
Good catch and good attempt at fix. I think the following is even "more" what is needed:

     if (IsNonPtrAccessChain(op) || op == SpvOpCopyObject) {
       if (!HasOnlySupportedRefs(u.inst->result_id()))
         return false;
     }
     else if (op != SpvOpStore && op != SpvOpLoad && op != SpvOpName)
       return false;

The goal is to make sure that we are restricting to variables which are ultimately only consumed by Loads, Stores or Names in order to simplify data dependence checking. We want to avoid variables consumed by OpFrexp, OpFunctionCall, etc.

We would want this change in both:

local_single_block_elim_pass.cpp
local_single_store_elim_pass.cpp

**Comment by antiagainst** [comment]
@greg-lunarg: Gotcha. Thanks for the suggestion! Done. :)

**Comment by antiagainst** [comment]
Hey @greg-lunarg, I'll merge this PR if you think it's fine now. :)

**Comment by greg-lunarg** [comment]
Yes. I think it is fine. Thanks for your fixes.

**Pull request merged**
