### PR TITLE
Use a struct (instead of tuple), with explicit member names.

### PR DESCRIPTION
**Pull request by Ace17**

### CODE REVIEW

**Review by s-perron — APPROVED** [review]

**Comment by s-perron** [comment]
Again, this will probably have to be rebased.

**Comment by Ace17** [comment]
ok, rebased.

**Comment by s-perron** [comment]
I'm not sure what is going on with the tests.  They all fail with the message:

```
[08:41:58][ERROR] Failed to clone GitHub repository
```

**Comment by Ace17** [comment]
> I'm not sure what is going on with the tests. They all fail with the message:
> 
> ```
> [08:41:58][ERROR] Failed to clone GitHub repository
> ```

Is it specific to this branch ?

**Comment by s-perron** [comment]
I believe it is an infra issue.  I'll try rerunning and how that it works.

**Pull request merged**
