### PR TITLE
linker: Allow modules to be partially linked

### PR DESCRIPTION
**Pull request by pierremoreau**
Fixes: https://github.com/KhronosGroup/SPIRV-Tools/issues/1144

### CODE REVIEW

**Comment by pierremoreau** [comment]
The RelWithDebInfo build using g++ timed out, but all the other builds were successful.

**Comment by antiagainst** [comment]
Hmm... It seems the performance of the Travis infrastructure is fluctuating again.

I restarted that job. Let's see what will happen.

**Comment by pierremoreau** [comment]
Thanks for restarting the job. I had some timeout on another pull request, but I need to fix some formatting, so that will restart the job there.

**Comment by pierremoreau** [comment]
Still the same build failing, but this time it is due to one of the unit test (spirv-tools-test_spirv_unit_tests), however that test is also failing on master.

**Comment by dneto0** [comment]
I suspect the conflict is a trivial conflict with the --verify-ids change.  I can resolve that locally.

**Comment by pierremoreau** [comment]
I would guess so as well; I initially had this series on top of the verify-ids one, and rebasing it onto master led to some conflicts, but I thought I was still better to have them separate.
Thanks for the review.

**Comment by dneto0** [comment]
Rebased, resolved conflict, and pushed into master as bdd6617fa

**Pull request closed without merging**
