### PR TITLE
spirv-lint: Add lint based on divergence analysis

### LINKED ISSUE #3196: [RFC] spirv-lint: A linter tool for SPIR-V
## Objective
We propose to add a new linting tool for detecting common semantic issues and bugs to the SPIRV-Tools project. This new tool, spriv-lint, will aid both developers by warning them about likely issues in their shaders, and existing automated tools like spirv-reduce that can sometimes produce semantically incorrect code. The main goal of this proposal is to find a good place to develop such features and it does not focus on the details of possible static analyses.

## Background
SPIRV-Tools contains two existing tools that are related to analyzing shader code for potential bugs -- the validator, spirv-val, and optimizer, spirv-opt. While spirv-val can detect many issues in SPIR-V code, it's designed with simple (mostly syntactic) checks in mind and produces only binary result: valid or invalid. However, it is often desired to generate warnings about likely bugs in code. For example, relying on undefined values in math operations and branching on the result may be fine according to the language specs, but is highly unlikely to be an intended behavior. Detecting such defects often requires analyses that are outside of the scope of the validator but are already used by the optimizer. Because these checks do not perform any optimizations or transformations, we propose to implement them in a separate tool.

## Motivation
Differences between shader compilers are often caused by different handling of undefined behavior in the input shaders. If that's the case, we want to automatically detect that a certain dubious code pattern is also detected in all the other shaders that may suffer from the same issue. We also want to make sure that our tools don't unintentionally introduce new undefined behavior when reducing failures with spirv-reduce. This is complementary to runtime checks that can be implemented within the LunarG runtime validation layer.

### Examples

1. Incorrect use of implicit derivatives. As per the SPIR-V specs, it is only valid to use implicit derivatives with uniform control flow. The DXC shader compiler can sometimes generate incorrect code with conditionally-executed OpKill or derivative instructions (e.g., OpImageSampleImplicitLod), while it's possible introduce undefined behavior in GLSL by conditionally discarding before sampling. 
Being able to quickly identify this issue would have saved us a lot of debugging, but doing so requires performing analyses that seems too difficult to simply hack together.
Even if we detect the code pattern described above, it is still a valid SPIR-V code as long as all threads take the branch uniformly and execute OpKill or the derivative, so we cannot simply issue a validation error. Emitting a warning seems much more appropriate in these case.  

2. Branching on undef SPIR-V uses similar semantics to LLVM when it comes to dealing with undefined values. Reading from an uninitialized variable produces a value with nondeterministic contents on each use. Changing branching on an undef to unconditionally taking one of the branches is a valid compiler optimization that can produce different results across different compilers. It is easy to introduce this extra difference in the generated code by using an automated reducer like spirv-reduce, but is a reduction step we would rather avoid.

3. The WebGPU-maintained list of sources of SPIR-V UB: https://github.com/gpuweb/gpuweb/issues/34.

## The Proposal
We propose spirv-lint as a new component of SPIRV-Tools. spirv-lint will generate warnings about potential bugs in the input shader code. We want to use the existing code in spirv-opt and add new analyses and checks that are specific to linting. We propose spirv-lint be a new tool as it's conceptually different from both spirv-val and spirv-opt and want to avoid polluting these two projects. Just like other linters and static analyzers, spirv-lint can produce false-positives, but using it is entirely-opt in. We recognize that generating many false positives is detrimental to user experience and intent for each check to be opt-in, implemented as a separate 'passes'.

### PR DESCRIPTION
**Pull request by dong-ja**
The primary purpose of this PR is to add the code from my prototype as a PR, for licensing reasons.
The commit history is messy, and the code is not especially clean.

Closes #3196.

### CODE REVIEW

**Comment by dong-ja** [comment]
Dependent on #4478 and #4465.

**Comment by kuhar** [comment]
@dong-ja  Can you rebase this? The diff contains many unrelated commits

**Comment by dong-ja** [comment]
Rebased so it only has the single commit. **This PR will not build as is. If you want to test it, you must rebase it on top of the two mentioned PRs.**

**Comment by dong-ja** [comment]
Rebased again, should build. You can cherry-pick the commits from #4478 to test the linter as a CLI program.

**Review by alan-baker — CHANGES_REQUESTED** [review]
It is difficult to review without more tests. Are those tests close to ready?

**Comment by kuhar** [comment]
I cannot merge this PR because it's marked as draft. I rebased the changes and opened an new PR instead: https://github.com/KhronosGroup/SPIRV-Tools/pull/4488.

**Pull request closed without merging**
