### PR TITLE
spirv-opt: Extend SetResultType and SetResultId functions

### LINKED ISSUE #3769: spirv-opt: Extend SetResultType and SetResultId functions in the Instruction class
The `SetResultType` and `SetResultId` functions, in the `Instruction` class, do not handle the case where the result type and result id are not yet in `operands_`. Therefore, the functions can be extended to cover that case.

### PR DESCRIPTION
**Pull request by andreperezmaselco**
Fixes #3769.

### CODE REVIEW

**Comment by andreperezmaselco** [comment]
@s-perron and @alan-baker, could you review it?

**Review by s-perron — CHANGES_REQUESTED** [review]
I've added a general comment on the strategy to the issue.  I think this is unsafe behaviour, and too easy for some one to make a mistake.

**Comment by afd** [comment]
I couldn't see @s-perron's comment, but I'm also not keen on this change.  @andreperezmaselco - I think you wanted it to make one of your spirv-fuzz PRs work a bit differently regarding how instructions are created, but as we discussed I'd prefer you to avoid that in the spirv-fuzz PR in any case.  Would you thus be OK to close this (and associated issue) @andreperezmaselco?

**Comment by andreperezmaselco** [comment]
OK, @afd. I'll close them.

**Pull request closed without merging**
