### PR TITLE
Fix chromium build

### PR DESCRIPTION
**Pull request by ShabbyX**

### CODE REVIEW

**Comment by jaebaek** [comment]
Thank you for working on it.

**Comment by ShabbyX** [comment]
@jaebaek No problem. Could you please add the kokoro:run label and once green, merge this?

**Comment by jaebaek** [comment]
Sure. Thanks!

**Comment by ShabbyX** [comment]
The build failure seems unrelated to this change. Looks like the repo is currently failing these tests.

**Comment by jaebaek** [comment]
Yeah, currently @dneto0 is working on it. Don't worry about it. I will land this CL after he fixes the issue.

**Pull request merged**
