### PR TITLE
check_symbol_exports on Python3, Mac

### PR DESCRIPTION
**Pull request by pow2clk**
subprocess.Popen returns byte data by default. Python2 was happy
to try to execute string operations on such data and hope for the
best, but python3 is more persnickety. Luckily, there's a simple
way to indicate to the Popen class that text data is wanted that
benefits the script. Just specifying universal_newlines will cause
the returned data to be text and also convert any system-specific
newlines to '\n' which the script relies on anyway.

Enabled on Mac as an incidental change after confirming that the
script works there just as well as it does on Linux.

It probably works on FreeBSD too, but I retired my BSD system years
ago. So I have no way to check.

Fixes https://github.com/KhronosGroup/SPIRV-Tools/issues/1645

### CODE REVIEW

**Comment by pow2clk** [comment]
Forgot to reference https://github.com/KhronosGroup/SPIRV-Tools/issues/1645 . I fixed it on the web interface. Maybe that's good enough?

**Comment by dneto0** [comment]
Are symbols on Windows really the same format as the Itanium mangling expected on Linux?

The check-symbol-exports was a spot check for namespace leakage.  I guess there was a possible hole on the Windows side, but I viewed it as low risk.

I'm happy to merge this if the bots pass.

**Comment by pow2clk** [comment]
I was surprised about Windows too. I confess though that all I did was plug this change in and run. Everything came back happy and the tests did run. So I guess so?

**Comment by pow2clk** [comment]
Turns out the Windows passing was a mirage. When the script finds it's not on a posix system, it pretends to pass and moves on. So patronizing!

**Comment by dneto0** [comment]
Rebased, squashed, and pushed into master as 878b3b400b2f

**Pull request closed without merging**
