### PR TITLE
Add validation for SPV_EXT_shader_atomic_float_min_max

### PR DESCRIPTION
**Pull request by jekstrand**

### CODE REVIEW

**Review by alan-baker — COMMENTED** [review]
Looks ok, but I'll wait to approve until https://github.com/KhronosGroup/SPIRV-Headers/pull/189 is merged and I can re-run the bots properly.

**Comment by alan-baker** [comment]
@jekstrand, sorry this got lost in the shuffle while waiting for the headers to get merged. Do you mind rebasing and resolving the conflicts?

**Comment by jekstrand** [comment]
@cmarcelo can you take care of this?

**Comment by cmarcelo** [comment]
> @cmarcelo can you take care of this?

Sure.

**Comment by cmarcelo** [comment]
@jekstrand rebased version in https://github.com/cmarcelo/SPIRV-Tools/tree/SPV_EXT_shader_atomic_float_min_max. I don't think I can update this PR, could you update it? Alternatively I can create a different one.

**Comment by jekstrand** [comment]
Done.

**Review by alan-baker — APPROVED** [review]

**Pull request merged**
