### PR TITLE
linker: Recalculate interface variables

### PR DESCRIPTION
**Pull request by karolherbst**
By resolving extern symbols Entry Points might access variables they hadn't declared before.

Side note: we might want to rename `RemoveUnusedInterfaceVariablesPass` as it's not removing variables, but instead recomputing them.

### CODE REVIEW

**Review by s-perron — CHANGES_REQUESTED** [review]
Could you add a test for this?  Otherwise this looks good.

**Comment by karolherbst** [comment]
> Could you add a test for this? Otherwise this looks good.

done

**Comment by karolherbst** [comment]
Mhh, it seems like that `Linkage` doesn't actually require the `Kernel` cap... but I guess this is more of a CL problem than GL/Vk?

**Comment by karolherbst** [comment]
did something happened to CI?

**Review by s-perron — APPROVED** [review]

**Pull request merged**
