### PR TITLE
Add a method in the types to check whether there is no decoration on a type.

### PR DESCRIPTION
**Pull request by Qining**

### CODE REVIEW

**Comment by Qining** [comment]
@antiagainst

**Comment by Qining** [comment]
@antiagainst  updated

**Comment by antiagainst** [comment]
+2

**Comment by dneto0** [comment]
I want to see tests for this kind of thing.

**Comment by antiagainst** [comment]
@dneto0: Oh, my fault. I should requested that. So, I write it here: #378.

**Pull request merged**
