### PR TITLE
Initial support for SPV_KHR_integer_dot_product

### PR DESCRIPTION
**Pull request by kpet**
- Adds new operand types for packed-vector-format
- Moves ray tracing enums to the end

- PackedVectorFormat is a new optional operand type, so it requires
  special handling in grammar table generation.

- Add SPV_KHR_integer_dot_product to optimizer whitelists.

- Pass-through validation: valid cases pass validation
  Validation errors are not checked.

Patch by David Neto <dneto@google.com>
Rebase and minor tweaks by Kevin Petit <kevin.petit@arm.com>

Signed-off-by: David Neto <dneto@google.com>
Signed-off-by: Kevin Petit <kevin.petit@arm.com>

### CODE REVIEW

**Comment by kpet** [comment]
I'd like to get the assembler/disassembler support in reasonably quickly to facilitate the development/release of upcoming Vulkan and OpenCL extensions if possible. There is more work needed on validation and I'm happy to sign up to contribute this. I'm also fine with leaving the partial validation support out of this first PR if this helps with reducing the review burden. Let me know what you prefer.

**Comment by dneto0** [comment]
This works for me, as described at https://github.com/KhronosGroup/SPIRV-Headers/pull/220

**Review by dneto0 — APPROVED** [review]

**Comment by dneto0** [comment]
This can only be merged when the headers PR is merged. (As close to simultaneously as practical.)

**Review by dneto0 — APPROVED** [review]

**Comment by kpet** [comment]
The headers PR has gone in. I've rebased this change, updated DEPS and it now seems to be passing all automated tests.

**Pull request merged**
