### PR TITLE
WIP: Add member initializations to fix GCC10 warning

### PR DESCRIPTION
**Pull request by dneto0**
See #3526

I don't have MinGW GCC 10.0 handy so I can't verify this actually fixes the problem.  It's just a guess.

### CODE REVIEW

**Comment by Biswa96** [comment]
In msys2/mingw64 environment, GCC 10 is used. There is a way to setup GitHub Actions with msys2. If allowed I can talk with someone who is familiar with it.

**Comment by Biswa96** [comment]
I have tested with mingw-w64-gcc 10.1.0. It shows same warning as follows:

```c
In file included from ../test/opt/instruction_test.cpp:21:
../source/opt/instruction.h: In member function 'virtual void spvtools::opt::{anonymous}::InstructionTest_OperandAsLiteralUint64_64bits_Test::TestBody()':
../source/opt/instruction.h:101:23: warning: '*((void*)& operand +32)' may be used uninitialized in this function [-Wmaybe-uninitialized]
  101 |     uint64_t result = uint64_t(words[0]);
      |                       ^~~~~~~~~~~~~~~~~~
```

There is a way to setup GitHub Actions with msys2 so that devs don't have to install the environment. If allowed I can talk with someone who is familiar with it.

**Comment by s-perron** [comment]
I'm guessing this solution does not work because the `SmallVector` class does not write to the memory in the class even if you initialize the vector to `{}`.  It probably just sets the size.

**Comment by s-perron** [comment]
Are we able to verify if this is still a problem?

**Pull request closed without merging**
