### PR TITLE
Add SPV_EXT_shader_image_int64

### PR DESCRIPTION
**Pull request by Tobski**
Relies on https://github.com/KhronosGroup/SPIRV-Headers/pull/170

### CODE REVIEW

**Review by alan-baker — CHANGES_REQUESTED** [review]
Needs tests.

**Comment by Tobski** [comment]
> Needs tests.

I've added some tests - hopefully those make sense and are sufficient? It wasn't clear how exactly to contribute new tests so I've somewhat winged it.

**Review by alan-baker — CHANGES_REQUESTED** [review]
It would be useful to have one successful case too. While we wait for the headers to get merged you could address the formatting issues if it's convenient.

**Comment by Tobski** [comment]
> It would be useful to have one successful case too.

There is already one success case in there - "ImageTexelPointer64Success". I can add more if you think that's useful?

> While we wait for the headers to get merged you could address the formatting issues if it's convenient.

Done!

**Comment by Tobski** [comment]
Ack, right. So because of the new addition of a new flags type for fragment shading rate, this is currently failing. Should be able to get #3943 in soon though given it's already approved and just waiting for sign off, then I'll rebase and this should be good to go...

**Review by alan-baker — APPROVED** [review]

**Comment by alan-baker** [comment]
The VS2015 is a flaky linker.

**Pull request merged**
