### PR TITLE
Fix -Wunreachable-code-aggressive.

### PR DESCRIPTION
**Pull request by pkasting**
Bug: chromium:1066980

### CODE REVIEW

**Comment by kenrussell** [comment]
For clarity: this impacts Chromium's build, as it pulls in SPIRV-Tools. See https://crbug.com/1066980 .

@alan-baker could you please review this? Thanks in advance.

**Review by alan-baker — APPROVED** [review]

**Comment by alan-baker** [comment]
@pkasting can you please fix the formatting issues and rebase on master?

**Comment by pkasting** [comment]
Are you referring to the CI-check-format error?  It seems to be complaining about a file I haven't touched.

**Comment by alan-baker** [comment]
Ok, just the rebase then so I can get a run of the buildbots.

**Pull request merged**
