### PR TITLE
Add option to validate after each pass

### PR DESCRIPTION
**Pull request by alan-baker**
* New command-line option to opt: --validate-after-all
 * Pass manager will validate after each pass it runs

Errors look like:
```
error: line 109: ID 54[%54] defined in block 43[%43] does not dominate its use in block 68[%68]
  %68 = OpLabel

error: line 0: Validation failed after pass merge-return
```

### CODE REVIEW

**Comment by alan-baker** [comment]
Especially useful when combined with -print-all.

**Comment by paulthomson** [comment]
Perhaps the name should be slightly different to clarify that it runs after each pass, not after all passes have run. E.g. `--validate-every-pass` `--validate-after-each` `--validate-all` `--validate-passes` But this might just be me.

**Comment by alan-baker** [comment]
> Perhaps the name should be slightly different to clarify that it runs after each pass, not after all passes have run. E.g. `--validate-every-pass` `--validate-after-each` `--validate-all` `--validate-passes` But this might just be me.

It was named after the llvm option -print-after-all. I guess we changed that to -print-all, but this option doesn't control the initial validation. Maybe `--validate-passes` is a better name.

**Comment by paulthomson** [comment]
Ah maybe `--validate-after-all` is fine then.

**Pull request merged**
