### PR TITLE
Remove ValidateOperandBaseType() for  OpenCL.DebugInfo.100

### PR DESCRIPTION
**Pull request by AlexeySotkin**

### CODE REVIEW

**Comment by AlexeySotkin** [comment]
@bashbaug, FYI.

**Comment by jaebaek** [comment]
@AlexeySotkin Could you please provide me with some information? e.g., why we need this change.

**Comment by jaebaek** [comment]
Oh I saw the commit message. Never mind.

Just one thing unclear for me is the DebugTypeVector.
You said "components of a vector also may be a typedef (uint)", but `uint` is a basic type that can be expressed by `DebugTypeBasic`. Am I wrong?

**Comment by AlexeySotkin** [comment]
> Just one thing unclear for me is the `DebugTypeVector`.
> You said "components of a vector also may be a typedef (uint)", but `uint` is a basic type that can be expressed by `DebugTypeBasic`. Am I wrong?

There is `unsigned int` the [basic types](https://www.khronos.org/registry/OpenCL/specs/3.0-unified/html/OpenCL_C.html#built-in-scalar-data-types) table, but not `uint`

> I checked [the vector types of OpenCL C](https://www.khronos.org/registry/OpenCL/specs/3.0-unified/html/OpenCL_C.html#built-in-vector-data-types) and their base types are parts of the [basic types](https://www.khronos.org/registry/OpenCL/specs/3.0-unified/html/OpenCL_C.html#built-in-scalar-data-types) that can be described by `DebugTypeBasic`.

I think it can but in [LLVM/Clang](https://github.com/llvm/llvm-project/blob/main/clang/lib/Headers/opencl-c-base.h) it is implemented as the following:
```
typedef unsigned int uint;
...
typedef uint uint4 __attribute__((ext_vector_type(4)));
```
[Here ](https://godbolt.org/z/YYEx8v48M) is how `uint4` is represented in LLVM IR. It preserves the typedefs. I think in C/C++ we can typedef almost any type.

**Comment by AlexeySotkin** [comment]
@jaebaek are all failures in CI caused by my patch?

**Comment by jaebaek** [comment]
Yeah. Some unit tests fail.

```
[----------] Global test environment tear-down
[==========] 5505 tests from 338 test suites ran. (13246 ms total)
[  PASSED  ] 5499 tests.
[  FAILED  ] 6 tests, listed below:
[  FAILED  ] ValidateOpenCL100DebugInfo.DebugTypePointerFail
[  FAILED  ] ValidateOpenCL100DebugInfo.DebugTypeQualifierFail
[  FAILED  ] ValidateOpenCL100DebugInfo.DebugTypeVectorFail
[  FAILED  ] ValidateOpenCL100DebugInfo.DebugTypeVectorFailComponentZero
[  FAILED  ] ValidateOpenCL100DebugInfo.DebugTypeVectorFailComponentFive
[  FAILED  ] AllOpenCL100DebugInfoFail/ValidateOpenCL100DebugInfoDebugTypedef.Fail/1, where GetParam() = ("%foo_name %dbg_src %dbg_src 1 1 %comp_unit", "Base Type")

 6 FAILED TESTS
  YOU HAVE 16 DISABLED TESTS
```

**Comment by s-perron** [comment]
This is stale.  I will close it.

**Pull request closed without merging**
