### PR TITLE
Spirv-fuzz: Add tests for MaybeGet* functionalities in fuzzer util

### PR DESCRIPTION
**Pull request by sliu-UIUC**
This PR will solve #4179 by adding unit testing for all maybeGet* functions in fuzzer_util. 

The following unit testing has been added and ready to review: 
* fuzzer_util_maybe_find_block_test.cpp
* fuzzer_util_maybe_get_bool_type_test.cpp
* fuzzer_util_maybe_get_float_type_test.cpp
* fuzzer_util_maybe_get_integer_type_test.cpp
* fuzzer_util_maybe_get_pointer_type_test.cpp
* fuzzer_util_maybe_get_struct_type_test.cpp
* fuzzer_util_maybe_get_void_type_test.cpp
* fuzzer_util_maybe_get_bool_constant_test.cpp
* fuzzer_util_maybe_get_integer_constant_test.cpp (test negative constants)
* fuzzer_util_maybe_get_integer_constant_from_value_and_type_test.cpp (test negative constants) 
* fuzzer_util_maybe_get_zero_constant_test.cpp (have issues)
* fuzzer_util_maybe_get_composite_constant_test.cpp
* fuzzer_util_maybe_get_float_constant_test.cpp (not sure how `words` would look like for a float type)

### CODE REVIEW

**Comment by sliu-UIUC** [comment]
I got ERROR: constant_shader.frag:14: '=' :  cannot convert from ' const int' to ' temp mediump uint' when I try to use `uint`. Should I try with a different percision? My current one is 
``` 
#version 310 es
precision highp float;
```

**Comment by sliu-UIUC** [comment]
Potential bug (or misuse on my end): 
The only issue I found out was with `fuzzer_util_MaybeGetStructType`. Consider the following shader script: 
```
%6 = OpTypeInt 32 1
%7 = OpTypeFloat 32
%8 = OpTypeStruct %6 %7
```
`fuzzer_util_MaybeGetStructType` ideally should take `ir_context` and `std::vector<uint32_t)(6,7)` as parameters and return 8 for the result id, but the following validation failed, as `OpTypeStruct` with the result id 8 cannot be found: 
```C++
ASSERT_TRUE(fuzzerutil::MaybeGetStructType(ir_context, std::vector<uint32_t>(6, 7))==8);
```
And in the implementation of `MaybeGetStructType`, since there cannot be function type ids in the vector parameter, it might be better to assert that function ids cannot appear in the vector.

**Comment by sliu-UIUC** [comment]
Questions related to `MaybeGetFloatConstant` and `MaybeGetIntegerConstant`. 

For `MaybeGetIntegerConstant`, I figured that for a positive integer, the test would be something like this example: 
frag script `int i = 100`
compiled shader: `%25 = OpConstant %20 100`

We have a id of 25 for this constant, so we should have: 
```
fuzzerutil::MaybeGetIntegerConstant(ir_context, transformation_context, 
  std::vector<uint32_t> {100}, 32, true, false) = 25;
```
where the `word` vector specify the value of integer with one word and 32 specify the width, this seems more trivial. But how do we get the id of negative integer. It seemed that negative integer is also 32 bit and should have 1 element in the word vector to specify its value, but how do we do that as the word vector consists of type `unsigned int`. 

Similarly with `MaybeGetFloatConstant`, it looks like float type is also 32 bit and you need at least 2 words for representing its integer part and decimal part, and an additional one for specifying whether the float constant is negative.

**Comment by sliu-UIUC** [comment]
For `MaybeGetZeroConstant` and `MaybeGetCompositeConstant`, where should I found `composite_type_id` and `scalar_or_composite_type_id`. There should be a corresponding ids for each value type, int, float, bool, vector, etc.

**Comment by afd** [comment]
> I got ERROR: constant_shader.frag:14: '=' : cannot convert from ' const int' to ' temp mediump uint' when I try to use `uint`. Should I try with a different percision? My current one is
> 
> ```
> #version 310 es
> precision highp float;
> ```
> 
> similar to `double`, which is a 64 bit. I probably need to have double type too for more comprehensive testing.

It's unlikely to do with precision and more likely to do with you relying on an implicit conversion from int to uint. In GLSL types are really explicit, so for example you can't do:

```
uint x = 2;
```

You have to do:

```
uint x = 2u;
````

where `2u` is an unsigned literal. You can use `uint(expr)` to convert `expr` from various types to `uint`.

Does that help?

**Comment by afd** [comment]
> Potential bug (or misuse on my end):
> The only issue I found out was with `fuzzer_util_MaybeGetStructType`. Consider the following shader script:
> 
> ```
> %6 = OpTypeInt 32 1
> %7 = OpTypeFloat 32
> %8 = OpTypeStruct %6 %7
> ```
> 
> `fuzzer_util_MaybeGetStructType` ideally should take `ir_context` and `std::vector<uint32_t)(6,7)` as parameters and return 8 for the result id, but the following validation failed, as `OpTypeStruct` with the result id 8 cannot be found:
> 
> ```c++
> ASSERT_TRUE(fuzzerutil::MaybeGetStructType(ir_context, std::vector<uint32_t>(6, 7))==8);
> ```

As a style point, I would write this as:

```
ASSERT_EQ(8, fuzzerutil::MaybeGetStructType(ir_context, {6, 7});
```

But you are right: I would expect this assertion to pass (in either form). Probably best if you update your PR to include a test with such an assertion, in the above form, and we can try it out locally if you point us to the specific line of code.

> And in the implementation of `MaybeGetStructType`, since there cannot be function type ids in the vector parameter, it might be better to assert that function ids cannot appear in the vector.

That's a good idea - could you add the assertion in your PR, and add a death test?

**Comment by afd** [comment]
> For `MaybeGetZeroConstant` and `MaybeGetCompositeConstant`, where should I found `composite_type_id` and `scalar_or_composite_type_id`. There should be a corresponding ids for each value type, int, float, bool, vector, etc.

As an example (and forgive me if there are typos in what follows!), if you have this:

```
%10 = OpTypeInt 32 0 // unsigned int type
%11 = OpConstant %10 0 // zero of unsigned int type
%12 = OpConstant %10 0 // another zero of unsigned int type - redundant, but allowed
%13 = OpConstant %10 1 // one of unsigned int type
%14 = OpTypeVector %10 2 // vector of two unsigned ints
%15 = OpTypeVector %10 4 // vector of four unsigned ints
%16 = OpConstantComposite %14 %11 %12 // the vector (0u, 0u)
%17 = OpConstantComposite %15 %12 %13 %12 // the vector (0u, 1u, 0u)
```

and suppose that there are no "irrelevant" facts, then:

`MaybeGetZeroConstant(ir_context, transformation_context, 10, false)` should return either 11 or 12 (it will probably return 11 with the current implementation but we don't guarantee this, so tests should not assume it).

`MaybeGetZeroConstant(ir_context, transformation_context, 14, false)` should return 16 (because it is a 2D zero vector)

`MaybeGetZeroConstant(ir_context, transformation_context, 15, false)` should return 0 (because there is no 3D zero vector declared)

`MaybeGetCompositeConstant(ir_context, transformation_context, { 12, 13, 12 }, 15, false)` should return 17 (because %17 declares exactly such a constant)

`MaybeGetCompositeConstant(ir_context, transformation_context, { 12, 13, 13 }, 15, false)` should return 0 (because no instruction declares such a constant)

Does that help to clarify things?

**Comment by sliu-UIUC** [comment]
> Does that help?

It surely does!

**Comment by sliu-UIUC** [comment]
> > Potential bug (or misuse on my end):
> > The only issue I found out was with `fuzzer_util_MaybeGetStructType`. Consider the following shader script:
> > ```
> > %6 = OpTypeInt 32 1
> > %7 = OpTypeFloat 32
> > %8 = OpTypeStruct %6 %7
> > ```
> > 
> > 
> > `fuzzer_util_MaybeGetStructType` ideally should take `ir_context` and `std::vector<uint32_t)(6,7)` as parameters and return 8 for the result id, but the following validation failed, as `OpTypeStruct` with the result id 8 cannot be found:
> > ```c++
> > ASSERT_TRUE(fuzzerutil::MaybeGetStructType(ir_context, std::vector<uint32_t>(6, 7))==8);
> > ```
> 
> As a style point, I would write this as:
> 
> ```
> ASSERT_EQ(8, fuzzerutil::MaybeGetStructType(ir_context, {6, 7});
> ```
> 
> But you are right: I would expect this assertion to pass (in either form). Probably best if you update your PR to include a test with such an assertion, in the above form, and we can try it out locally if you point us to the specific line of code.
> 
> > And in the implementation of `MaybeGetStructType`, since there cannot be function type ids in the vector parameter, it might be better to assert that function ids cannot appear in the vector.
> 
> That's a good idea - could you add the assertion in your PR, and add a death test?

Yes, I will do that.

**Comment by sliu-UIUC** [comment]
> > For `MaybeGetZeroConstant` and `MaybeGetCompositeConstant`, where should I found `composite_type_id` and `scalar_or_composite_type_id`. There should be a corresponding ids for each value type, int, float, bool, vector, etc.
> 
> As an example (and forgive me if there are typos in what follows!), if you have this:
> 
> ```
> %10 = OpTypeInt 32 0 // unsigned int type
> %11 = OpConstant %10 0 // zero of unsigned int type
> %12 = OpConstant %10 0 // another zero of unsigned int type - redundant, but allowed
> %13 = OpConstant %10 1 // one of unsigned int type
> %14 = OpTypeVector %10 2 // vector of two unsigned ints
> %15 = OpTypeVector %10 4 // vector of four unsigned ints
> %16 = OpConstantComposite %14 %11 %12 // the vector (0u, 0u)
> %17 = OpConstantComposite %15 %12 %13 %12 // the vector (0u, 1u, 0u)
> ```
> 
> and suppose that there are no "irrelevant" facts, then:
> 
> `MaybeGetZeroConstant(ir_context, transformation_context, 10, false)` should return either 11 or 12 (it will probably return 11 with the current implementation but we don't guarantee this, so tests should not assume it).
> 
> `MaybeGetZeroConstant(ir_context, transformation_context, 14, false)` should return 16 (because it is a 2D zero vector)
> 
> `MaybeGetZeroConstant(ir_context, transformation_context, 15, false)` should return 0 (because there is no 3D zero vector declared)
> 
> `MaybeGetCompositeConstant(ir_context, transformation_context, { 12, 13, 12 }, 15, false)` should return 17 (because %17 declares exactly such a constant)
> 
> `MaybeGetCompositeConstant(ir_context, transformation_context, { 12, 13, 13 }, 15, false)` should return 0 (because no instruction declares such a constant)
> 
> Does that help to clarify things?

Yes, I think that helps a lot. Thanks.

**Comment by sliu-UIUC** [comment]
> Questions related to `MaybeGetFloatConstant` and `MaybeGetIntegerConstant`.
> 
> For `MaybeGetIntegerConstant`, I figured that for a positive integer, the test would be something like this example:
> frag script `int i = 100`
> compiled shader: `%25 = OpConstant %20 100`
> 
> We have a id of 25 for this constant, so we should have:
> 
> ```
> fuzzerutil::MaybeGetIntegerConstant(ir_context, transformation_context, 
>   std::vector<uint32_t> {100}, 32, true, false) = 25;
> ```
> 
> where the `word` vector specify the value of integer with one word and 32 specify the width, this seems more trivial. But how do we get the id of negative integer. It seemed that negative integer is also 32 bit and should have 1 element in the word vector to specify its value, but how do we do that as the word vector consists of type `unsigned int`.
> 
> Similarly with `MaybeGetFloatConstant`, it looks like float type is also 32 bit and you need at least 2 words for representing its integer part and decimal part, and an additional one for specifying whether the float constant is negative.
> 
> P.S: also with function:
> 
> ```c++
> uint32_t MaybeGetIntegerConstantFromValueAndType(opt::IRContext* ir_context,
>                                                  uint32_t value,
>                                                  uint32_t int_type_id);
> ```
> 
> It seemed like it cannot find the id of negative integer with only unsigned value parameter.

The vector part is resolved. It's a typo that makes `{}` to `()`. Rather than having two elements, using `()` initialized an array with first number indicating the number of elements and the second one the value for each element. It's just a typo.

**Comment by sliu-UIUC** [comment]
This is superceded by #4284.

**Pull request closed without merging**
