### PR TITLE
Add structs to eliminate dead input components

### PR DESCRIPTION
**Pull request by greg-lunarg**
Will eliminate all trailing members of input struct that are not
referenced.

### CODE REVIEW

**Review by Keenuts — COMMENTED** [review]
Hello!

How would that change affect struct array stride?
Looks like we define the max size by walking the use, and if it's an OpAccessChain with constant indice, truncate the struct.
What would happen if the struct is part of a uniform buffer?
Or if the type is used into another type?

If those cases are handled, would it be useful to add tests for them?

**Review by s-perron — APPROVED** [review]

**Comment by s-perron** [comment]
> How would that change affect struct array stride?

In this case, the variable is of type struct, so there is no array of structs.  
> Looks like we define the max size by walking the use, and if it's an OpAccessChain with constant indice, truncate the struct.
What would happen if the struct is part of a uniform buffer?

This pass looks specifically for variables that are in the input storage class.  If it wants to change the size of the variable, it creates a new type, and changes the type of the variable.  Other variables will not be changed.  Maybe the commnets are not clear enough that it changes the type of the variable.

However, there is another pass (dead member elimination) that removes any unused members from uniforms.  The members of the struct do not determine the layout of the struct.  The layout is determined by the decorations.  See [decorations](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#Decoration) are used for that. See `ArrayStride` and `Offset`.

When you "remove" the member of a struct, all we are doing is removing a way of referencing the member.  We are not changing the layout.


> Or if the type is used into another type?

Again, the old type is not deleted.  A new type is created.

**Comment by greg-lunarg** [comment]
@Keenuts Do you concur with @s-perron 's approval? If so, can you please approve?

**Review by Keenuts — APPROVED** [review]

**Comment by Keenuts** [comment]
Sorry, yes of course approved 😀 Thanks for the explanations Steven!

**Pull request merged**
