### PR TITLE
Add new checks to validate arithmetics pass

### PR DESCRIPTION
**Pull request by atgoo**
New operations:
- OpDot
- OpVectorTimesScalar
- OpMatrixTimesScalar
- OpVectorTimesMatrix
- OpMatrixTimesVector
- OpMatrixTimesMatrix
- OpOuterProduct

### CODE REVIEW

**Comment by dneto0** [comment]
Waiting for bots to go green.

**Comment by dneto0** [comment]
Funny thing:   When I rebase against master and retest, this new code catches a problem in the MARKV-codec tests.

[ RUN      ] Markv.VectorTimesScalar
error: 71: Expected float vector type as type_id: VectorTimesScalar
error: 0: Unable to encode to MARK-V.
.../test/comp/markv_codec_test.cpp:101: Failure
      Expected: SPV_SUCCESS
      Which is: 0
To be equal to: spvSpirvToMarkv(ctx.context, words.data(), words.size(), options.get(), markv_binary, &spv_text_comments, nullptr)
      Which is: -4
/build/dneto/v/vokuhila/third_party/spirv-tools/test/comp/markv_codec_test.cpp:147: Failure
Expected: (nullptr) != (markv_binary), actual: 8-byte object <00-00 00-00 00-00 00-00> vs NULL
[  FAILED  ] Markv.VectorTimesScalar (3 ms)

**Comment by dneto0** [comment]
Please rebase and retest.

**Comment by dneto0** [comment]
Bots have failed, showing the need to rebase and update the markv codec tests.

**Comment by atgoo** [comment]
Bots are green.

**Comment by dneto0** [comment]
Rebased, squashed, and pushed into master as c6dfc1188065

**Pull request closed without merging**
