### PR TITLE
val: re-add ImageMSArray validation

### PR DESCRIPTION
**Pull request by Keenuts**
This has been removed in #4752, but not added since.

### CODE REVIEW

**Comment by alan-baker** [comment]
Have you tested this against Vulkan CTS?

**Comment by Keenuts** [comment]
> Have you tested this against Vulkan CTS?

No, and that's a very good point! I'll do that.

**Comment by Keenuts** [comment]
> Have you tested this against Vulkan CTS?

I tried to run it, but it crashed in the middle (query-pool.txt set). So it's a partial run, done in 2 parts (I ignored the `query-pool.txt` set).

- `query-pool.txt` crash is the same with and without the change, so probably unrelated.
- the 2 sides have a few failures (50-ish), but they are the same, so probably unrelated.

So I'd say it passes the vulkan CTS? At least with some confidence?

**Comment by alan-baker** [comment]
> > Have you tested this against Vulkan CTS?
> 
> I tried to run it, but it crashed in the middle (query-pool.txt set). So it's a partial run, done in 2 parts (I ignored the `query-pool.txt` set).
> 
> * `query-pool.txt` crash is the same with and without the change, so probably unrelated.
> * the 2 sides have a few failures (50-ish), but they are the same, so probably unrelated.
> 
> So I'd say it passes the vulkan CTS? At least with some confidence?

How did you run it? You can just use buildPrograms -v to build all the SPIR-V with validation enabled. Not sure if you tried that or an actual device run, but wanted to mention in case you weren't aware.

**Comment by Keenuts** [comment]
> How did you run it? You can just use buildPrograms -v to build all the SPIR-V with validation enabled. Not sure if you tried that or an actual device run, but wanted to mention in case you weren't aware.

I followed the wiki, and used `./deqp-vk --deqp-caselist-file=$repo/external/vulkancts/mustpass/main/vk-default.txt`. (The whole think took something like 3 to 4 hours, and ran on my GPU.

Didn't knew about `vk-build-programs -v`, and it is indeed a good think to know,thanks 😊 This worked without any issues (`ran ./vk-build-programs -v`) and all  were marked as passed (8210834), and 6 as not supported (AND it didn't took 3 hours to run 😊)

**Review by alan-baker — APPROVED** [review]

**Pull request merged**
